### ISSUE TITLE
32 bit version very slow with P3D, 64 bit version works perfectly.

### ISSUE THREAD

**Issue by NatalieGates** [albar965/littlenavmap#1052]
I use the latest version of LNM for MSFS and P3Dv5. When I open the P3D version it is very sluggish but to the point where I can't use it. So I use the main version (MSFS, 64  bit) and it works perfectly the only problem is I can't see my plane information obviously, but since I fly on vatsim I can at least see my plane on the LNM. 

I wish I could get the 32 bit version to work as well as the 64 bit version because atm I only fly in P3D.

I use all default settings and only import my flight plan from simbrief.

Any advice would be appreciated or if it's running as expected please close this issue. :)

**Comment by albar965** [comment]
Both, the 32-bit and 64-bit build should normally run the same. At least they do here.

Maybe the weather display is the issue in the 32-bit since it connects to P3D and fetches airport weather via SimConnect.

Try to disable the map weather symbols in LNM menu `Weather` -> `Airport weather source`. Set this to anything but `Simulator`.

Alex

**Comment by NatalieGates** [comment]
That worked perfectly, thanks!

**Comment by albar965** [comment]
You're welcome. :slightly_smiling_face:
