### ISSUE TITLE
Deleting individual waypoints on a procedure instead of removing the entire procedure

### ISSUE THREAD

**Issue by jessy0506** [albar965/littlenavmap#1067]
Hi,

As often is the case in real life, flights on long arrivals tend to receive a shortcut based on traffic density at the arriving airport. As a result the Top of Descent point starts earlier than planned, to compensate for less track-miles. It would be nice to be able to project this in LNM too, by just removing the procedure waypoints you don't expect flying over, to calculate an accurate Top of Descent. 

However, removing any waypoint in a procedure gets rid of the procedure in its entirity.

**Comment by albar965** [comment]
The only solution to this is to turn a procedure into a list of waypoints before editing (like menu -> `File` -> `Export Options` does. This is good for simple SID and STAR. I plan to implement this function one day. But this has a lot of limitations. Restrictions are dropped and some leg types cannot be converted.

Editing a procedure is impossible due to the insane complexity behind it.

Alex

**Comment by albar965** [comment]
You can convert procedures to a list of waypoints in the 3.0. betas which allows editing. Editing full procedures is not doable.
