### ISSUE TITLE
Unable to load new scenery library

### ISSUE THREAD

**Issue by merspieler** [albar965/littlenavmap#1069]
So I'm running the latest lnm version on NixOS 23.11.
I'm using flightgear as simulator but also have XP12 demo installed. Afaik nither is supported by lnm yet.
Before I removed the old XP11 demo I've created a fake directory structure where I put the nav data files in.
Parsing these worked in the past somehow.
Now "Scenery Library" > "Load Scenery Library (no simulator)" is greyed out.
How can I point lnm to my fake XP11 structure so it can parse the up-to-date data without me having to re-install the XP11 demo?

**Comment by albar965** [comment]
> Afaik nither is supported by lnm yet.

Sorry, wrong. LNM supports XP12 already since early betas of XP 12.

> Now "Scenery Library" > "Load Scenery Library (no simulator)" is greyed out.

LNM checks for the XP11 or 12 installation files/folders. The installation is be disabled if these are not present. I changed this some time ago so that these files are required to detect XP.

Create a text file ´$HOME/.x-plane/x-plane_install_11.txt` (or 12) containing a single line which is the path the to X-Plane installation. This file is normally created by the X-Plane installer and will enable the loading option in LNM.
Also make sure to use the latest LNM.

**Comment by albar965** [comment]
Ebenso Frohe Weihnachten und einen guten Rutsch ins neue Jahr!
