### ISSUE TITLE
Performance File Speed TAS Difference to the G1000

### ISSUE THREAD

**Issue by Lewis2023** [albar965/littlenavmap#1084]

**Comment by Lewis2023** [comment]
Hi
I work with the record of a performance file for a C172S.
The climb Speed TAS is always 6 kts higher as the TAS value in the G1000. During the Cruise phase the value is also higher but only about 3 kts.
Conditions: No Wind, Max Weight, Vy (IAS) = 72 KIAS constant with FLC to 7000 FT. 
Process: LNM shows at the beginning, 500 ft AGL a value of 79 kts and goes up to 86 kts at the altitude of 7000 FT.
At the end I have an average climb speed of 86 kts and this is to high.
What I am doing wrong?

**Comment by albar965** [comment]
LNM uses the average which is good enough to calculate the climb. Do not confuse this with the actual values shown in the cockpit. They will differ after take off and before TOC.

TAS being above IAS and rising with altitude is normal due to thinner air at altitudes. The values are directly read from the simulator and therefore reliable. I use TAS in the perf because it is independent of wind.

**Comment by Lewis2023** [comment]
Grüezi Alex
Ok, I have taken the term "average" into account. If I fly from 0-12'000
then the average calculated by LNM  is about 86 KTAS.

*Let's look at LNM in the starting phase*: 500 FT above the ground: the map
shows IAS =72 kts and TAS = 78. A calculation gives TAS = 73 kts for the
standard Temp 15°C.
The shown 78 kts should be an average from 0 to 1000 FT ? This makes no
sense.
How do you calculate this 78 kts?
Edi

Am Fr., 26. Jan. 2024 um 15:48 Uhr schrieb Alexander Barthel <
***@***.***>:

**Comment by albar965** [comment]
> How do you calculate this 78 kts?

As I said above: It is not calculated but taken from every simulator as is. Average is calculated over time and you spend more time at the higher altitudes since climb is slower there. So the higher TAS is more dominant in the average.

Data sources:
- X-Plane dataref: `sim/flightmodel/position/true_airspeed`
- SimConnect (MSFS, P3D and FSX): Variable `Airspeed True`

BTW, next time read the text in the issue template:
> Delete this text after reading before posting the issue.

What simulator do you use BTW and what G1000 is this?

Alex

**Comment by Lewis2023** [comment]
Sim is MSFS2020 and G1000nxi, all latest version

**Comment by albar965** [comment]
Does it also appear with stock G1000 or other aircraft?
I still doubt this is an issue with LNM. I take the values as they are without any conversion.

**Comment by Lewis2023** [comment]
ok, I will try the same testfile with gms50/gtn750 and with another plane
to see if there is the same pattern. I will give you a short feedback

Alexander Barthel ***@***.***> schrieb am Sa. 27. Jan. 2024
um 11:54:

**Comment by Lewis2023** [comment]
Cessna 172S_G1000: Difference of 6 kts in TAS value G1000 and LNM is constant. All other values, especially fuel consumption are the same and near to the POH.
Cessna 208: Same effect.
**_Now the good news:_** I have tested with Kodiak100_G1000, Bonanza ATC36_GTN750, Tecnam2012P_G1000: No difference in TAS, all values are the same.
Fazit: 
1. Not a problem of LNM, must be one with MSFS Cessna's profiles.
2. For the Cessna 172 and Caravan: I think for the calculation of the fuel consumption this difference of 6 kts does not count.
BTW: The fact that your program runs the performance in the background during the flight is a great feature for all which fly live weather. Merging makes it even better after each flight. Thanks for this great program!

**Comment by albar965** [comment]
Thanks for getting back about this. :+1: 

I have no idea what they are doing there. Normally the TAS is calculated and provided by the simulator. I'd expect aircraft add-ons to use and show this value and not calculate their own.

My last flight in X-Plane did show no differences. Values were spot on with the aircraft (A319).

Alex

**Comment by albar965** [comment]
Checked MSFS with the stock DA-62 and saw no differences bigger than one knot from TAS up to 8000 ft.
Most likely a problem with the aircraft systems.
Closing. Feel free to reopen if you see issues.
