### ISSUE TITLE
Whitespace before/after Whazzup File URL causes Test function to become inactive or fail

### ISSUE THREAD

**Issue by hdinthkld** [albar965/littlenavmap#1089]
Confirmed with 2.8.12

When entering the URL for the Whazzup file URL users are unable to test the connection if there is whitespace at the beginning:
![image](https://github.com/albar965/littlenavmap/assets/377271/bf5b0f0c-3659-43a8-8043-ab6b34f5a55b)

In addition if whitespace is entered after the URL the test fails:
![image](https://github.com/albar965/littlenavmap/assets/377271/17893102-fbdb-4d2f-bf92-692e5bed7117)

Whitespace is not permitted in a URL so it would be preferred if this is automatically cleared out once the user exits the text box.

The online group I'm a member of often receives requests from users who have trouble with this.

**Comment by hdinthkld** [comment]
I don't program in Qt but maybe the below is of help:
https://doc.qt.io/qt-5/qstring.html#trimmed

**Comment by albar965** [comment]
The URL is encoded internally which results all spaces converted to '%20' (and other special characters too). Spaces **inside** the URL are allowed but trailing or leading should be better trimmed by LNM.

The disabled test button is already fixed in the 3.0.x beta releases.

I'll check all paths and URLs and trim them. I already use the trim function in a lot of places but there are still a few missing.
