### ISSUE TITLE
Default plugin in webserver

### ISSUE THREAD

**Issue by miuratv** [albar965/littlenavmap#1129]
Hi, it's possibile to load by default the "ol-map" plugin in the web based interface?   Every time i reload the page it gets deactivated.  I'd like to have it always on.

**Comment by albar965** [comment]
OL as default make sense IMO.

The only small issue I see is that the OL map always jumps back to coordinates 0/0 when starting or switching pages. There are also no updates if a user changes the map settings or adds user features.

Any way to add an auto update and fix the 0/0 issue?

Alex

**Comment by u-an-i** [comment]
0/0 I guess is doable.  
  
About the update: this might be the limitation I remember: the ol-map uses tiles and caches them.
The cache might have to get invalidated completely or cleverly where necessary.  
  
I'll have a look if i can figure these things out.

**Comment by KOKAProduktion** [comment]
Hiho guys!

Please forgive my silence. A lot has happened and I'm currently quite occupied but I'm always reading the stream and dreaming on re-joining you guys someday :)

I understand that you'd like to modify the packaged ol-map JS bundle in order to fix its static initialization.
The source repo is [KOKAProduktion/littlenavmap-openlayers](https://github.com/KOKAProduktion/littlenavmap-openlayers) 
and the lines you're probably looking for are here: 
https://github.com/KOKAProduktion/littlenavmap-openlayers/blob/6723fee95b4d5055c87b37ee71c15635b3faea37/src/index.js#L48

I'm sorry that I can't take up any tasks at the moment to help out myself but please let me know if you have questions or issues. I'll try my best to answer/help as much as possible...

All the best and high five for keeping the flame burning! You guys are awesome!

Cheers!

**Comment by albar965** [comment]
Just merged  #1131 and cherry picked this into `release/3.0` but see no changes. Still starting at 0/0 and even a reload takes me back to old map.

**Comment by u-an-i** [comment]
@albar965 when you switch between menus (Map, Aircraftn Flightplan, ...)  the map now remains in its last state.  
  
The initial load when (re-)loading the whole webpage is not affected.  
  
 I need the PR in the ol repo from @KOKAProduktion for that.

**Comment by albar965** [comment]
Ok. Will wait.

**Comment by u-an-i** [comment]
yes, I already got the message :)

**Comment by u-an-i** [comment]
@albar965 this one is done in `release/3.0` branch now.
