### ISSUE TITLE
enhanced waypoint describe on XP12 [def request]

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1176]
in FixXP1200 specification there is a new column for the integrated name for the waypoint
may add it to here
![image](https://github.com/user-attachments/assets/fb2d7563-5551-4e6b-b5de-8e35e32aec8f)
![image](https://github.com/user-attachments/assets/e0ff9dfc-1de9-4e48-b877-3f168255edff)
[XP-FIX1200-Spec.pdf](https://github.com/user-attachments/files/16443259/XP-FIX1200-Spec.pdf)

**Comment by albar965** [comment]
Oops. I looked in the spec but did not catch this one. Thanks for reporting. :+1:

**Comment by Eyderoe** [comment]
thanks for your efforts

**Comment by albar965** [comment]
Waypoint names added to  compiler, navdata search, information, tooltip and flight plan table.
A future navdata update is needed if using Navigraph data to see the names. Otherwise they'll show up for XP12 right away.

![image](https://github.com/user-attachments/assets/d3a6521c-592c-4cdf-b4b6-04e7fef27130)
