### ISSUE TITLE
(Mac) 3.0.11 "Little Navmap.app" will damage your computer. You should move it to the Trash.

### ISSUE THREAD

**Issue by e8vww** [albar965/littlenavmap#1196]
I just downloaded the latest version 3.0.11, extracted it over top of the old version. Now I get a message "Little Navmap.app" will damage your computer. You should move it to the Trash.

Screenshot below
<img width="328" alt="Screenshot 2024-10-13 at 11 27 18 PM" src="https://github.com/user-attachments/assets/665f0ed4-ffff-431e-bde6-2bb616a320b4">

How do I fix this?
Where can I download older versions?

**Comment by 6639835** [comment]
Hello, please click cancel and find Privacy and Security in your settings, scroll down and you will find out how to open it. Good luck.

**Comment by albar965** [comment]
The error message is ridiculous hyperbole of Apple's pseudo-security measures. You can ignore it. Downloading older versions will not help.

See here in the user manual: [Installation - macOS](https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/INSTALLATION.html#macos) and
[Clearing the Quarantine Flag on macOS](https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/XPCONNECT.html#clearing-the-quarantine-flag-on-macos).

Not sure if this helps since I have no device capable running latest macOS.

**Comment by albar965** [comment]
Does this help?
https://www.idownloadblog.com/2024/08/07/apple-macos-sequoia-gatekeeper-change-install-unsigned-apps-mac/

**Comment by u-an-i** [comment]
I'm unhappy to be able to chime in: I have the "same" issue in Windows using Edge for > 1 year now. I always reported to Microsoft as safe (trusting @albar965 and believing the build is safe) but until now I still receive the SmartScreen Filter warning it is I believe.

@albar965 perhaps you can report to Microsoft as its author. Perhaps GitHub can build the release and thus confirm its safe due to it being able to scan the sources, also GitHub belongs to Microsoft enabling integration to SmartScreen Filter. If GitHub can do that but you don't know how I might try to have a look.

![image](https://github.com/user-attachments/assets/4c7a4119-3eb8-4906-929c-bd95a5755bac)

![image](https://github.com/user-attachments/assets/589f589c-1185-43a5-8248-e3b9499be44a)

![image](https://github.com/user-attachments/assets/9e063a9e-223d-45d7-b51f-6deaccbea0ed)

**Comment by albar965** [comment]
> perhaps you can report to Microsoft as its author.

Already did. MS does not care. I'll try again for 3.0.11.

I also put this into the FAQ:
 [After downloading in Windows Edge I see an error message Program isn’t commonly downloaded. Make sure you trust Little Navmap](https://albar965.github.io/littlenavmap-faq.html#windows-download)

This is still harmless compared to the pseudo-security circus that macOS raises.

Alex

**Comment by albar965** [comment]
BTW: I'd rather use a better browser than Edge which does not play these games. Firefox, Vivaldi, Brave, etc.
