### ISSUE TITLE
P3Dv5

### ISSUE THREAD

**Issue by Budlake** [albar965/littlenavmap#1203]
The 32bit version of LittleNavMap does not work very well in P3Dv4+. 
When will there be a 64bit version that does work?

Thanks

Mike

**Comment by albar965** [comment]
Can you tell me what "does not work very well" means and why a 64 bit version can fix this?

Alex

**Comment by Budlake** [comment]
Because LittleNavMap is hesitant, a lot of time, particularly when manually moving the map. Furthermore, it, annoyingly, remembers input so instead of moving to the required position it changes scale and position seemingly on a whim until it gets to where you want it, thus taking more time to settle on the desired scale and position.
It appears that it only has limited resources to do what is required of it. I also notice that rather strangely, LittleNavmap is only available in 64 bit format for MS20 and X Plane. It seems that it believes that P3D is a 32bit system, which it is not.

**Comment by albar965** [comment]
Thanks. I see. 

This might help to speed up the program:
- Deselect `Flight Simulator` in menu `Weather` -> `Airport weather source`. This is an issue with the SimConnect interface which fetches weather from the simulator and can cause stutters.
- Menu `Map` -> `Default Map Detail` to avoid overflowing the map with unneeded features.
- Disable all in menu `View` which you don't need like airways or airspaces.
- Use map projection `Mercator` in menu `View` -> `Projection`. This is faster than `Spherical`.
- Disable all unneeded services like the web server in menu `Tools`.
- Deselect unneeded weather services in options on page `Weather`

A 64-bit version will definitely not help with this and I'm not going to change it since it is too much effort. I'd rather keep the 32 bit to support all "legacy" simulators like FSX and P3D.

**Comment by Budlake** [comment]
Thanks Alex,

 

Your suggestions appear to have done the trick. All appears well.

 

Thank You.

 

Mike

 

Mike Monk 

~~~~~~~~~~~~~~~~~~~~~~~~~

tel (Thai):   +66 876 290 427

WhatsApp:  +66 876 290 427

Skype:         +44 1392 58 0575 (please email first)

email:          ***@***.*** ***@***.***> 

stay well – stay safe

~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by albar965** [comment]
Glad hear! Happy flying!

Alex
