### ISSUE TITLE
Qt5Core.dll

### ISSUE THREAD

**Issue by donbrindles** [albar965/littlenavmap#124]
I've downloaded Qt5Core.dll...can you tell me please where and how I should install this - I've installed latest version of Little NavMap, but when I try to run it I'm told Qt5Core.dll is missing.

Thanks, Don

**Comment by albar965** [comment]
Hi Don,

the correct Qt5Core.dll is included in the archive and is placed in the same directory as the littlenavmap.exe. I just checked this to be sure. Maybe it got lost during installation?

Try to download again and reinstall.

What system you have? Windows 7 or 10? 64 bit or a 32 bit system?

Where did you install it? Do not put the program into "Program Files" since there are a few restrictions.

Alex

**Comment by albar965** [comment]
Does it work? Can we close the issue?
Alex

**Comment by albar965** [comment]
Feel free to reopen if the problem persists.
