### ISSUE TITLE
Aircraft trail/track length limit & export

### ISSUE THREAD

**Issue by curVV** [albar965/littlenavmap#131]
I'm doing a long distance route in a Cessna. I'd like to have the track/trail saved after each day's flight so I can see the overall route flown at the end.

Two issues I'm experiencing with it:

1: There is a limit to the length of the trail. How can it be increased?
2. As a result of issue #1 I started exporting each day's flight plan as GPX, which showed the track in Google Earth. But after some number of days the exported GPX no longer shows the most recent progress. I tried exporting to RTE as well, but same problem.

Thanks!

**Comment by albar965** [comment]
It is currently limited due to performance reasons and cannot be increased for now. I could display huge fine grained tracks but doubt that this is worth the optimization effort.

The GPX export includes the current flight plan and the (pruned) track. Exporting as RTE does not help since this is only a flight plan format.

I'll add a setting in the option dialog where you can change the maximum track length also to unlimited.

The track is saved in the file
`C:\Users\YOURUSERNAME\AppData\Roaming\ABarthel\little_navmap.track`
You can put this aside after a days flight and look at it later by putting it back in place if that helps.
Alex

**Comment by curVV** [comment]
Hi Alex.

I am backing up the .track file already. Bu after the entire route I'm going to have to stitch it all together (and drop the overlapping bits) in order to get the full picture... somehow.

Anyway, thanks for adding this!

Great app!

Cheers.

**Comment by albar965** [comment]
Fixed with 1.6.7 which adds a setting in the options dialog that allows to set the maximum number of points.
