### ISSUE TITLE
Edit altitude at flight plan waypoints

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#166]
Allow the user to overcome the single cruise altitude restriction.

Edit altitude at each waypoint of the flight plan

**Comment by AntoineLeo** [comment]
I wish to have it too !

**Comment by albar965** [comment]
It is unlikely to happen given the complexity of the elevation calculation (think about all kind of altitude restrictions).

**Comment by AntoineLeo** [comment]
Personnaly it's one of the few feature I miss the most comparing to vfrflight from Łukasz Kulasek.
I'm not sure, but what about temporary disabling features that rely on fixed altitude design when a user would edit the altitude of a waypoint. These features could be reactived by setting up a fixed altitude for the fly plan.

**Comment by albar965** [comment]
Have to see. Maybe I can add it like the procedure altitude restrictions. Kind of. But it is either working together with the procedure restrictions or not. Not going to add another mode, sorry. This would make maintenance a mess.
Alex

**Comment by AntoineLeo** [comment]
I totally agree with you. I'm mostly a VFR guy and I have to admit that the first time I met littlenavmap I saw it more as a IFR flight planner. Maybe it was, I don't know. But certainly IFR and VFR are really different flight to manage. Why not splitting feature like altitude restriction, waypoint altitude and so on in two littlenavmap mode (IFR vs VFR ). Futhermore the user already have to set it. Would that make any sense ?

**Comment by albar965** [comment]
LNM was more a VFR planner at the beginning and evolved to an IFR planner.
Using two modes does not make sense IMO and would cause an additional work of a month or more. And there are not so many differences. Nope.
Alex

**Comment by Gfurst** [comment]
Sorry for not finding this before posting the duplicate above, but I agree with the above, it could be a really useful feature, I don't see it needing to be any different from how altitude restrictions already work for procedures. 
As mentioned in the issue I posted, I would like to see restriction values for custom user made waypoints (as opposed to only elevation). If you look at visual chart area routes, there will often altitude restrictions either advisable or enforced (due to nearby IFR traffic).

**Comment by albar965** [comment]
No problem. The duplicates are sometimes hard to find.

> I don't see it needing to be any different from how altitude restrictions already work for procedures.

It is different. Believe me. I already had too much surprises like "Ooops. This is way more complicated that thought". Altitude restrictions are monotonic in procedures. Means always lower or equal to predecessor in approaches and STAR and reversed in SID. This makes error checking and path calculation much easier. While procedures are mostly free of errrors users can enter whatever they want. ¯\\_(ツ)\_/¯

If I add this it will also cover user waypoints. This doesn't make a big difference then.

**Comment by Gfurst** [comment]
I would imagine it would work the same way, restriction in user made fixes, as high as it can to altitude until you reach cruise, or as low it can on descent. Varying on this should be expected on sim according to player criteria, other traffic and such. I can imagine some oddities occurring, like going above flight cruise to make up for some obstacle restriction, or going on a descent before finishing the ascent, these could be hard to figured out. I could help out drawing the logic if you want to.
Now for custom waypoints the user puts in the flight plane I can only imagine its a set height. By the way, this is all without taking into consideration flight regime/fuel calculations, since change in these regimes quite a lot of variation, it can never take it as being that accurate.

**Comment by simonedmondson** [comment]
I came across this feature request while doing a search for this. Just wanted to put my 2c ...

While it would be a really neat feature to have, I use VFR flight plans as rough routes that are designed for exploring and sightseeing and I have begun to set my route altitude to the **highest** point on the route that I will need to reach during the journey, which is nice information to have. 

I usually fly my VFR at different heights, quite often hugging the ground so I can get good views, so therefore...

- would it be possible to draw plan elevation profile data which hugs the topology [ground elevation + chosen height above ground level] (not sea level) for the duration of the flight? Perhaps impossible to develop in a timely manner because you might need to take plane performance characteristic into account ans so on and so on... might be countless factors to consider for all I know! 

- It would be cool to provide the 'highest ground point on the route' information to the plan summary (somewhere?) as added flight data - this might be calculated automatically from topographic info that is already shown on the elevation profile. It would also allow the app to warn the user if they have set a plan altitude below minimum required for safe flight.

Small things, but I thought I'd contribute my own thoughts.

Finally, thanks for developing such an amazing tool!! I've been using it a lot since I bought MSFS 2020 so I will need to donate. Cheers.

**Comment by ezanchi** [comment]
This would be a really nice feature.

**Comment by daheise** [comment]
>     * would it be possible to draw plan elevation profile data which hugs the topology [ground elevation + chosen height above ground level] (not sea level) for the duration of the flight? Perhaps impossible to develop in a timely manner because you might need to take plane performance characteristic into account ans so on and so on... might be countless factors to consider for all I know! [edit: I guess this is pretty much the same as the original request but uses ground level as an automated elevation caculation?]

I use the "Leg safe altitude" for this purpose. If you want "higher resolution" you can just add waypoints.

**Comment by albar965** [comment]
Duplicate of #295. Arbitrary altitudes will not be done.
