### ISSUE TITLE
XPLANE 10

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#181]
SEEMS XP 10 not support this littlenavmap

**Comment by albar965** [comment]
Sorry, no. It is not supported and will not since it is too much effort for an old platform.

You can get LNM running with a few tricks that are explained here in the forum:
https://forums.x-plane.org/index.php?/forums/topic/129621-little-navmap-release-163-x-plane-support/&page=3&tab=comments#comment-1247689
See also the following posts in that thread.

Alex

**Comment by albar965** [comment]
Closing now. Too much effort to adapt to a recent simulator.
