### ISSUE TITLE
X-Plane 11.10 FMS format cycle number not saved

### ISSUE THREAD

**Issue by andrewbernard** [albar965/littlenavmap#190]
With a current Navigraph subscription, and LittleNavmap 1.8.3 updated with the Navigraph FMS data manager, when exporting to the X-Plane 11 format, X-Plane 11.10 shows a warning dialog when you use such a flight plan saying the cycle is 0 but the current Navigraph data is cycle 1713. Examining the FMS files, there is no cycle information in them.

Running the apps on Windows 10, Steam version of X-Plane.

**Comment by albar965** [comment]
Hi Andrew, 
this has two reasons where one bug is already fixed by me and the other one can be fixed by you:
1. LNM uses the wrong cycle information from the simulator database (X-Plane) instead of the navigation database (Navigraph). This is already fixed in development and LNM shows a warning dialog if the cycle is missing.
2. Older versions of LNM did not store the cycle data in the simulator database. This is already fixed in 1.8.3.

_You should reload your scenery database in LNM. That should solve the problem._

If that fixes it you can close the issue since 1. is already solved and will come with an update soon.
Thanks for reporting,
Alex

**Comment by andrewbernard** [comment]
Hi Alex, reloading scenery database as suggested worked, and the 1.84 release solves issue 1. Thanks!

**Comment by albar965** [comment]
Hi Andrew, thank you for the feedback. Good to know it is working now.
