### ISSUE TITLE
Exporting Flight plan to Garmin GTN

### ISSUE THREAD

**Issue by Bill721** [albar965/littlenavmap#191]
After I create a flight plan using stars and sids it looks great in Littlenavmap, but when I export it to Garmin GTN it only shows the starting and ending location.  None of the waypoints?  Is that correct or am I doing something wrong?

New User
Bill

**Comment by andrewbernard** [comment]
I have the same issue. I suspect you have to define the waypoints in the plan in the GTN 750 waypoint database for it to recognise them. This is why just today I asked if we could see the lat/lon for user defined waypoints so we can create them in the GTN 750 as a manual process. I may be entirely wrong about this!

**Comment by albar965** [comment]
It should not show the start and destination only. Do you get a message about locked waypoints?  Normally there is no need to create a user defined waypoint database since only a few waypoints are locked and can be deleted.

Please attach the exported flight plan to this issue and tell me which AIRAC cycle is used. Also, check if you use the latest Garmin trainer 6.41.
Alex

**Comment by Bill721** [comment]
Andrew thanks for the quick reply.  At least I’m not doing anything wrong…  I wish it would work easily because I love the GTN I just wish they would have used Navigraph data.  I fly on Vatsim and the GTN database is so outdated.  You have a great product with it being tied to Navigraph data, maybe someday it will easily port over to GTN if GTN ever lets it happen.

**Comment by albar965** [comment]
@Bill721: it does work easily. I tested this a lot when doing flights in the Jrollon Jetstream which has a perfect  GTN integration. I have to delete one or a two locked waypoints, sometimes select another procedure but apart from that it does well here. There is no solution for the locked waypoints due to different navdata cycles. I cannot do anything about it.

**Comment by Bill721** [comment]
I’ve attached the FP.  If I try to load in GTN or in p3dv4.1.  All I see are the KMEM and KLIT airports no other waypoints.  I don’t get any messages.

 

Thanks Bill

**Comment by albar965** [comment]
I  cannot see the file. If attaching does not work send it to my by email. My address is on my home page: https://albar965.github.io/
Best is to save the plan as PLN and GFP and send me both files. 
Alex

**Comment by Bill721** [comment]
Not sure why you can’t receive them and load them into GTN or Little Navmap.  I added a text version also this time.

 

Bill.

**Comment by albar965** [comment]
The  flight plan does not contain any waypoints. Only start, destination, a SID and an approach. Go to the options dialog on tab `Flight Plan` and deselect `Export navaids and airports as user defined waypoints ...` since this option does not allow to save procedures with the flight plan. You have to select them manually in the device.

If it is working correctly the file should look like
```FPN/RI:DA:KMEM:D:ELVIS3.WTWOO:AA:KLIT:AP:I04R.MOMTE```
If the GTN cannot load the procedures you will see a warning.
Alex

**Comment by Bill721** [comment]
Ok thanks so much

**Comment by Bill721** [comment]
It worked I was doing it wrong….  I was Export as Garmin GTN instead of Reality XP GTN.  It’s working.  Thanks so much for the assistance….

 

Bill

**Comment by Bill721** [comment]
Thanks for all you help and the great product....  Merry Christmas.

**Comment by albar965** [comment]
Glad it is working now. A Merry Christmas to you too.
Alex
