### ISSUE TITLE
Request Level-d 767 Flight Plan Format and Feelthere/Wilco Embraer's Flight Plan Format

### ISSUE THREAD

**Issue by ricardo404** [albar965/littlenavmap#206]
Hello alba965, i'am enjoying of the your project of the perfect open source flight plan for simulation. But I would like to request the flight plan format for B767 Level-d and Feelthere/Wilco Embraer's to your programand will be grateful to all who use these aircraft. 
  If you need someone to translate to Brazil-Portuguese, I'm sure to help you by just telling me how it's done.
 Thank you for your response and success in your project.
 Ricardo
 Brazil

**Comment by albar965** [comment]
Hi Ricardo,
thank you for the offer. See here in the LNM wiki regarding translation: https://github.com/albar965/littlenavmap/wiki/Translating . Nobody is translating to Portugese yet.
Related issues are #136 and #135.

Regarding the flight plan formats: You can do me a favor and attach any available documentation (if copyright permits) and example files. This would help a lot since I do not own these files. You can also sent any documentation or examples by email.
Best regards,
Alex

**Comment by ricardo404** [comment]
Thanks alex!. I sent some information and requests to your email. Thank you

**Comment by albar965** [comment]
Flight plan examples
[leveld.zip](https://github.com/albar965/littlenavmap/files/1622375/leveld.zip)
[feelthere.zip](https://github.com/albar965/littlenavmap/files/1622376/feelthere.zip)

[Flightplan Export to FeelThere B73x](http://fsbuild.com/forum/viewtopic.php?t=1467)
