### ISSUE TITLE
FAA sectional charts map theme

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#278]
Try to create a Marble map theme that allows to display the FAA sectional charts for VFR.
Format is GeoTiff.

https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/vfr/

**Comment by rvernica** [comment]
I found this set of FAA charts for Little Navmap [here](https://forum.mistymoorings.com/index.php?topic=4272.msg36956#msg36956)

**Comment by albar965** [comment]
Thanks but the charts are already linked in the LNM Avsim support forum: [New maps for LNM](https://www.avsim.com/forums/topic/548994-new-maps-for-lnm/).
Not sure if this ticket is still needed but I can still add support for GeoTiff later. Have to see.
Alex

**Comment by rvernica** [comment]
Thanks, Alex. Good to know. It might be worth including these maps with the LNM package. They are handy for USA users who are used with SkyVector. 

Moreover, FAA includes a World VFR chart, see [here](https://skyvector.com/?ll=44.67125724233048,3.387451183351464&chart=301&zoom=12&fpl=undefined) This chart is not included in the linked package, but you could consider including it and even setting it as the default to start with since it is a world-wide aeronautical chart.

**Comment by julianpoma** [comment]
I am trying the linked US VFR charts on the latest version of LNM (2.8.7), but the maps are a bit slow to load when zooming/moving around and the resolution is not the same (low) vs Skyvector, which is much snappier. Maybe this issue could help with that?

**Comment by albar965** [comment]
I cannot fix external map speeds. 

I see no sense to use maps like SkyVector in LNM anyway since all the needed navaids, airspaces, airways and whatnot are already shown by LNM and provided tooltips and more.
