### ISSUE TITLE
Download and display winds aloft

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#283]
- [x] Download GRIB files from NOAA or read the X-Plane one. Related to #6 
- [x] Show wind barbs on the map
- [x] Show optional tooltips for barbs with all wind layers
- [x] Show wind in elevation profile
- [x] Show average wind for cruise altitde
- [x] Consider average wind for cruise altitude in fuel calculation

https://en.wikipedia.org/wiki/GRIB

www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2018080206/WAFS_blended_2018080206f06.grib2

http://nomads.ncep.noaa.gov/txt_descriptions/grib_filter_doc.shtml

NDFD GRIB2 Decoder: https://www.weather.gov/mdl/degrib_home

X-Plane URLs:

https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?dir=%2Fgfs.2019021206&file=gfs.t06z.pgrb2.1p00.f003&lev_700_mb=1&lev_250_mb=1&var_UGRD=1&var_VGRD=1

https://ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2019021206/WAFS_blended_2019021206f06.grib2

**Comment by World4Fly** [comment]
If you don't know already, there exists a C API from the European Centre for Medium-Range Weather Forecasts (https://confluence.ecmwf.int//display/ECC/ecCodes+Home) which can read GRIB files. I changed their iterator example a few weeks ago so that it processes winds aloft data. The NOAA also provides a web API (http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?dir=%2F) which allows to subset the area, select a pressure level and variables so you can generate a download link only for winds aloft data which would reduce download sizes.

Example: `http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t18z.pgrb2.0p25.f000&lev_550_mb=on&var_UGRD=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2018080218`

**Comment by albar965** [comment]
Thank you for the links. Very helpful. 
I'll see if I can use the C API. It has to compile on Win, Linux and macOS. Will also check out the web interface.
Alex

**Comment by Gulliver54** [comment]
Hi Alex,
After obtaining weather info as intended, is it possible also, when zooming in on a airport, to see a wind arrow over the airfield pictogram indicating the wind direction at that moment. Only vissible from let say 40nm? Perhaps a bit closer for performance reasons?

**Comment by albar965** [comment]
Already done for #6. I show the usual meteorological symbols: Colors for IFR, VFR, etc. situation, circle fill for cloud cover like Skyvector and additionally wind barbs showing direction and speed.
Alex
 
Example: VFR, 3/4 cloud cover. wind from WSW, around 15 knots
![grafik](https://user-images.githubusercontent.com/15254956/44616582-dc781d00-a841-11e8-9ffe-2561d7899ebb.png)

**Comment by albar965** [comment]
Done. ActiveSky support forr high altitude wind will come later with 2.6.

**Comment by albar965** [comment]
The wind forecast (updated four times a day at the source) can be loaded from X-Plane or NOAA. 

Wind barb grid at selected altitude:
![grafik](https://user-images.githubusercontent.com/15254956/59594792-11f93a00-90e4-11e9-918a-40134d5e037b.png)

Wind barbs at flight plan waypoints:
![grafik](https://user-images.githubusercontent.com/15254956/59594753-fa21b600-90e3-11e9-9741-cb41a7424f2f.png)

**Comment by Gulliver54** [comment]
Wow, great stuf.
in sweet anticiption.....for the update
