### ISSUE TITLE
AviTab map export

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#310]
Add an image export function for [AviTab](https://github.com/fpw/avitab)

```
{
  "calibration": {
    "latitude1": 51.8425,
    "latitude2": 44.831,
    "longitude1": -8.4895,
    "longitude2": -0.7134,
    "x1": 0.1722338204592902,
    "x2": 0.541660487940095,
    "y1": 0.11333186101295643,
    "y2": 0.9629301675667267
  }
}
```
![eick-lfbd_night](https://user-images.githubusercontent.com/15254956/46580865-93101580-ca1c-11e8-8ae5-d377fa935a44.png)

**Comment by fpw** [comment]
That's a cool idea - AviTab can import Mercator maps and use them as moving map in the cockpit or 3D EFBs. If you suggest a more sophisticated format to add geo-referencing information to PNGs, I could integrate a parser for that into AviTab so that the exported format can be used in other applications as well. For example, AviTab already supports GeoTIFFs.

**Comment by albar965** [comment]
Hi,
Sorry for the delay I'm "deep diving" into some really annoying bugs here. :-/

GeoTiff sounds great if you support that already. Could be useful for other programs too.
Qt can do Tiff anyway. I just have to find out how I can get the georeferencing data into the metatags.
Alex

**Comment by albar965** [comment]
@fpw  What is the meaning of the values below?
```    
    "x1": 0.1722338204592902,
    "x2": 0.541660487940095,
    "y1": 0.11333186101295643,
    "y2": 0.9629301675667267
```
Could not find anything in the documentation. What image format and filename is expected?
Alex

**Comment by fpw** [comment]
@albar965 The ((x1, lon1), (y1, lat1)) and ((x2, lon2), (y2, lat2)) tuples translate from world coordinates to coordinates inside the image file. I used float coordinates instead of pixels to support vector formats like PDF as well. (0, 0) is the top left of the image and (1, 1) is the bottom right in xy space.

**Comment by fpw** [comment]
For the file name - it should be a copy of the image name with an additional .json extension, for example myMap.png.json

**Comment by albar965** [comment]
@fpw: So, for displaying the whole image x1=0, y1=0, x2=w, y2=h.
Where w and h are image dimensions in pixels.
This would be OK, right?
Alex

**Comment by fpw** [comment]
@albar965  No, the coordinates are normalized so that (0, 0) to (1, 1) always covers the whole image. (0.5, 0.5) would be the center of the image.

**Comment by albar965** [comment]
I see. Thanks for the quick answers. For now I prefer the JSON and PNG over GeoTiff. A bit easier to implement for me.
Alex

**Comment by fpw** [comment]
Sounds great, thanks!

**Comment by fpw** [comment]
I can load the examples successfully, thanks a lot! Which map projection do the images use? It looks like the position calculated by AviTab is slightly offset to the south as if the image uses a Lambert instead of a Mercator projection. In the attached image, the aircraft is actually standing on the blue airport.

![avitab](https://user-images.githubusercontent.com/5798899/51397232-0dceed80-1b41-11e9-84fd-5b71e3a1f5e8.jpg)

**Comment by albar965** [comment]
Thanks for testing and the feedback. The projection is a Mercator for sure. I even show a warning dialog if the user has the wrong projection (LNM uses only spherical and Mercator).
In my last tests the aircraft was positioned correctly. Will check again. Maybe I'm using a wrong offset from 
the window. Probably also have to test far South/North situations.
Alex

**Comment by fpw** [comment]
I used your EDFE_EDX_3 example file and positioned my aircraft on an EDHL runway for the above screenshot.

**Comment by albar965** [comment]
Will check. BTW: Thanks for also supporting Linux! Makes testing for me much easier. :-)
Alex

**Comment by albar965** [comment]
@fpw: Hi Folke,
I looked again at the export, tested a few ones and cannot find a distortion or any other errors. EDHL is south of the cyan/blue dot indicating the Lübeck city center. Looking OK to me.

I'll release a RC for 2.2.4 soon and will drop you a line.

Alex

![grafik](https://user-images.githubusercontent.com/15254956/51441715-20296280-1ccc-11e9-9206-36c09c3ce6be.png)

![grafik](https://user-images.githubusercontent.com/15254956/51441722-46e79900-1ccc-11e9-9dec-f7b83ceadd9f.png)

**Comment by fpw** [comment]
My mistake then, sorry! I thought the blue dot indicated the airport position and not the city center.

**Comment by albar965** [comment]
Kein Problem. :)

**Comment by albar965** [comment]
Hi Folko,
here's a release candidate: https://www.avsim.com/forums/topic/549357-little-navmap-224rc1/

I hope I can get the window size limitation out in the future so you can save arbitrary image sizes.
Alex

**Comment by fpw** [comment]
Did a few tests and it works perfectly! Thanks a lot. I posted in the forum about it: https://forums.x-plane.org/index.php?/forums/topic/169403-new-avitab-feature-in-littlenavmap/
