### ISSUE TITLE
Load flight plan with command line parameter

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#431]
Add more options for startup:

- [x] Load flight plan by route description like `EGHJ SAM Q41 SILVA M605 POL N601 GRICE EGPC` or simply `EGHJ EGPC`
- [x] Load flight plan file
- [x] Load aircraft performance

**Comment by cgrey000** [comment]
@albar965 - I was going to open an issue for command-line support before I saw this. Rather than create a quasi-duplicate, I'd add my request to this...

Be able to pass parameters via command line for departure and destination ICAO and aircraft profile file to load.  Example:

littlenavmap.exe  --depart-KEWR --destination-KTPA --profile-BE58

The above would pre-populate when LNM opens, but still allow for a flight plan to be created.

Thanks for considering.

**Comment by albar965** [comment]
I updated the issue. The route description part should also cover your use case for departure and destination.
Alex
