### ISSUE TITLE
Highlight online ATC-frequency inside tab "Com" 

### ISSUE THREAD

**Issue by Gulliver54** [albar965/littlenavmap#436]
Hi Alex,
Can you highlight the Online ATC frequency's inside tab "Com". 
Quick reference when approaching a busy airport like; EDDM EDDF EHAM
![07-22-01](https://user-images.githubusercontent.com/33782220/61638799-6d49b980-ac9a-11e9-845f-c87bcf7e6c67.jpg)

**Comment by albar965** [comment]
There is no connection between online center and airport. The ident before the first underscore might help but is not consistent. Some use the three letter notation (IATA BOS vs. ICAO KBOS) in VATSIM. IVAO always seems to use four-letter notation. This would leave some gaps since I don't have IATA codes. Not sure.
Alex
