### ISSUE TITLE
Display traffic and centers of VATSIM, IVAO and own servers

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#45]
Load files here: 
http://status.vatsim.net/status.txt
https://ivao.aero/softdev/ivai.asp

https://ivao.aero/ViewDocument.aspx?Path=/
https://doc.ivao.aero/apidocumentation:whazzup
DATA URL http://api.ivao.aero/getdata/whazzup/whazzup.txt

Make download URLs configurable in options dialog for other organizations.

**Comment by jarangmandi** [comment]
Can I suggest that you don't lock this functionality to VATSIM, but make it configurable so that the status file (whazzup file) can be picked up from a place of the user's choosing?

There are many private organisations who run their own FSD servers which produce a status file in a similar format.

**Comment by albar965** [comment]
Hi Andrew,
please attach files/examples to this ticket. I do not fly online myself and certainly need help and testers to implement this.
Alex

**Comment by jarangmandi** [comment]
An example file taken from our server this evening was is attached (names edited out, but structure intact). Most of the pilots were near the Seskatchewan / Manitoba / US border. I (the ATC presence) was at EGGD).

The file is generated every 30 seconds by the server. It's possible (depending on the client sim that the user is connected to and how it manages AI aircraft when connected to one of these servers) that there'll be an overlap between the aircraft that you pick up from there and the content of this file so you may need some logic to eradicate duplicates - which will probably be the ones from here.

The server software we're using which generated this file is modified slightly from the standard "FSD" software, but the content has moved very much towards that you'll see in the VATSIM link you have above (additional fields for each connection). When I get a little longer, I'll give you a list of what each of the fields mean - or if that's not possible, a list of what the ones I know mean - in both this and the VATSIM file if you need it!

Happy to help with this in any way I can...

Andy

**Comment by albar965** [comment]
Hi Andy,
thank you for the file.
if you have any documentation for the attached file around please link or attach.
Alex

**Comment by Aeroworx** [comment]
A file I use to parse the Whazzup.txt for a map display, just an example.

**Comment by jrsantos05** [comment]
Alexander, I was wondering if you found a way to pull the VATSIM connections into littlenav map?   It would be a great tool to use to see what controllers are online by having the boundaries light up or something that shows us they are controlling their areas.

**Comment by albar965** [comment]
Work on this subject has not yet begun. I fix bugs now and there are still #210 and #179 left. Next is #3 and then I'll start working on the online stuff.

**Comment by jrsantos05** [comment]
awesome! littlenav map is amazing sir.  It is most certainly going to have me send in a donation for such a great product.  I was using FSCommander and this blows it away!

**Comment by albar965** [comment]
All implemented but have no clearance from IVAO or VATSIM yet.

**Comment by albar965** [comment]
All in this discussion: Please contact me (email here https://albar965.github.io/) so I can send you a beta.
Alex

**Comment by bilkaPek** [comment]
Hi Alex
could you incorporate a new whazzup format
according to the exact structure of the "client" on db  _LNM_ format
because I work with my own whazzup for my VA
the Ivao or Vatsim format are not very practical in my opinion,
this will allow anyone wishing to generate whazzup files for easier integration with LNM.
Sam.

**Comment by albar965** [comment]
Hi Sam,
what software is that? Is it widespread?
The table `client` contains only users/aircraft. Centers are in the table `atc`.
Alex

**Comment by bilkaPek** [comment]
hi Alex
`what software is that? Is it widespread?`
I do not use any software,
I generate the whazzup file from the information of my database of users in flight,
the problem that currently arises and that to generate the whazzup file
I must respect the structure of IVAO or vatsim so that the flight data can correspond to the insertion of information in the database.table (little_navmap_onlinedata.client)

what I suggest and create an option LNM format to read a file whazzup according to the structure of the table clients

```
LNM Format Example:
value 1 = value line 1
value 2 = value line 2
value 3 = value line 3
....

vatsim && ivao to table.client Example:
value 1 = value line 1
value 2 = value line 5
value 3 = value line 2
```
![capture68](https://user-images.githubusercontent.com/16308214/45047110-6a40dd00-b078-11e8-9c4f-7534d259f596.PNG)


![capture66-1](https://user-images.githubusercontent.com/16308214/45047127-762c9f00-b078-11e8-87ed-4b1e87251404.png)

this will have the advantage that all having a VA will be able to generate a Whazzup file to see its drivers online from LNM

Sam.

**Comment by albar965** [comment]
@andreasmn : Nothing wrong on your side. This is currently a limitation of LNM and will be fixed in a future release. The task is covered by #236 for release 2.4.
Alex
