### ISSUE TITLE
Need airspace boundaries for online networks

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#490]
#### Will check for 2.8 (and next 2.7 alpha):

- [X] Import IVAO boundaries from JSON
- [x] Import VATSIM centers GeoJSON from [VATSpy Data Project](https://github.com/vatsimnetwork/vatspy-data-project). **I suppose this is the official source. Anybody please interject if not.**
- [x] Resolve current Online Center (updated periodically while flying) names to geometry fetched from above

----
#### Old Notes

LNM displays online centers as circles since the real boundaries are not available to me. 

A new feature was introduced in the 2.4 LNM versions which allows to assign real boundaries for centers:

See [Online Airspaces](https://www.littlenavmap.org/manuals/littlenavmap/release/2.4/en/SCENERY.html#load-scenery-library-online-airspaces).

I do not have access to these files from the online networks. Note that the files have to be in [OpenAir](http://www.winpilot.com/UsersGuide/UserAirspace.asp) format.

I'd like to put package in the [littlenavmap.org download section](https://www.littlenavmap.org/downloads/) if somebody can provide this data to me.

**Comment by ltoenning** [comment]
Speaking for VATSIM: This might be difficult. 
Normally all countrys managing their own sector-file which containing all sectors with different dependencies. (I haven't checked if LNM can handle these). 

Recently many vACCs started to use a tool called GNG (Global NAV Generator) which has a global database where every vACC can edit their sectors and sector-borders where fitted with edits for the neighbours. Most of the vACCs using this are listed here: http://files.aero-nav.com/

This datafiles aren't in OpenAir format so far, but I can try to contact the GNG-admin if he can implement a OpenAir-format export.

**Comment by albar965** [comment]
Hi Lars,
thank you for the link. This looks like the best collection so far. 
I know the used format (the name slipped my mind at the moment, LOL) and plan to support it in future versions for [user airspaces](https://www.littlenavmap.org/manuals/littlenavmap/release/2.4/en/SCENERY.html#user-airspaces) in LNM.

Providing the data in OpenAIR format would be terrific since it would enable this functionality for users right away. Would be great if you could ask the admin.
Alex

**Comment by b-faller** [comment]
So I did some work and wrote a small Python script to convert the data from the [VATSpy Data Project](https://github.com/vatsimnetwork/vatspy-data-project) into the OpenAir format. So far it works okay but there is still room for improvement.

Preview: 
![preview](https://user-images.githubusercontent.com/12356362/94945591-33e61e00-04db-11eb-9b65-5e73938c14e3.png)

However, a couple things would be nice to have:
- Many mappings for prefixes are missing in the original dataset so `CLE_04_CTR` does not point to the KZOB airspace boundary and is therefore not rendered. I added a small custom_mappings.json to be able to fix some of these issues. A better way would be to use only prefixes for matching instead of exact matches for each airspace, e.g. if an airspace named `CLE_S` exists show it for all callsigns/positions on VATSIM starting with `CLE_S` and an airspace named `CLE` matches all other positions starting with `CLE`. Basically a longest prefix match. Maybe the same for a suffix could be helpful too for different airspaces based on FSS/CTR? I think something along `CLE_S_CTR` (exact match), `CLE_S*` (prefix match), `CLE_S*FSS` (prefix and suffix match) would do well.
- The ability to designate UIRs airspace as UIR airspace type which is already in LNM. Maybe this is already possible via OpenAir?
- Instead of creating the same airspace for all callsigns/positions, define a mapping table so that multiple callsigns/positions can share the same airspace definition because the current file contains already around 100k lines …
- Maybe increase the zoom level at which online airspaces show, for centers I think it's a bit low?

I did put the script on [GitLab](https://gitlab.com/bfaller/vatsim-airspace-openair) if you want to take a look at it.

**Comment by albar965** [comment]
@b-faller Thank you a lot and sorry for the late reply. I'm currently in MSFS adaption and bug fixing craze for LNM. Give me a few days and I'l have a look at it. 
Is there also a way to extract IVAO data?

**Comment by b-faller** [comment]
@albar965 No problem, that's more important right now for sure. I did setup CI so that it always builds a user airspace file every 30 days so that it incorporates changes from upstream. I haven't found a way to run it on each upstream commit yet, if anyone knows how to do that please chime in. Anyway, a current file should now always be available [here](https://gitlab.com/bfaller/vatsim-airspace-openair/-/jobs/artifacts/master/raw/vatsim_airspaces.txt?job=build).

IVAO works mediocre because most centers share the callsign so it uses the same definition from VATSIM. As long as the airspace is identical for IVAO and VATSIM this should not be a problem, however, if they would not match the airspace boundary for some reason (maybe due to differing area of responsibility?) I can't solve this without a change in LNM or separate files (the callsign -> airspace mapping is shared/non-injective between IVAO and VATSIM airspaces). For IVAO I also don't have public sources.

**Comment by paulparkervogo** [comment]
file provided by b-faller was very useful as I see many airspace boundaries of online centers on VATSIM. However, as already pointed out by b-faller is many centers have different callsigns for same airspace. For example I see HOU_CTR correctly, but when the controller logs in as HOU_81_CTR, I see a big circle. I would like to suggest provide an editable field after callsign in Online Centers table where user (in this case me) can add the binding. For example, whenever I see a big circle where i expect to see a boundary shape of center, I can go and add the actual airspace name from the airspace file. 

For example if I see HOU_81_CTR, I can add HOU_CTR in the editable field next to it to get correct airspace. You can save the binding in a file automatically per callsign.

**Comment by albar965** [comment]
@paulparkervogo I'll see what can be done. Best way is to apply some automatic/fuzzy matching. Maybe allow a user to add matches center<->callsign manually as well.

**Comment by Quentin-M** [comment]
Hey, inquiring on whether there's been any movement on this. I believe this is the most requested feature on LNM!

**Comment by albar965** [comment]
> Hey, inquiring on whether there's been any movement on this. I believe this is the most requested feature on LNM!

I plan to look into this for 2.8. I certainly have the data for IVAO (but not the import code yet). Will also look into the Vatspy project linked above. But no promises as usual.

**Comment by Quentin-M** [comment]
Thanks a lot @albar965! 

I've chatted briefly with Mark at Volanta who said that SimAware (map.vatsim.net) apparently led an initiative to publish some of the USA APP sectors publicly, which is why they display the best boundaries.

**Data**
https://api2.simaware.ca/api/livedata/countries.json
https://api2.simaware.ca/api/livedata/firs.json
https://api2.simaware.ca/api/livedata/uirs.json
https://api2.simaware.ca/livedata/firboundaries.json
https://api2.simaware.ca/livedata/traconboundaries.json
https://api2.simaware.ca/api/livedata/live.json
https://api2.simaware.ca/api/livedata/onlinefirs.json
https://api2.simaware.ca/api/livedata/tracons.json
https://api2.simaware.ca/api/livedata/locals.json
https://api2.simaware.ca/api/livedata/sigmets.json
https://api2.simaware.ca/api/livedata/airports.json

![image](https://user-images.githubusercontent.com/1332289/153301493-1d308ad8-0387-4443-aef9-bd07bfa4ae9d.png)

**Comment by albar965** [comment]
Thanks for the links.

**Comment by albar965** [comment]
@Quentin-M and @b-faller Unfortunately I cannot find anything that allows to connect the callsigns from [vatsim-data.json](https://data.vatsim.net/v3/vatsim-data.json) to the boundary files. Boundary types are also missing.
No idea how to fix this for VATSIM.

**Comment by b-faller** [comment]
> @Quentin-M and @b-faller Unfortunately I cannot find anything that allows to connect the callsigns from [vatsim-data.json](https://data.vatsim.net/v3/vatsim-data.json) to the boundary files. Boundary types are also missing. No idea how to fix this for VATSIM.

The callsigns can be connected with this API endpoint: https://api.vatsim.net/api/map_data/. Specifically the `VATSpy.dat` file. In it there are two sections `[FIRs]` and `[UIRs]`. They have the structure:

| ICAO   | Name                              | Callsign Prefix | Fir Boundary |
|--------|-----------------------------------|-----------------|--------------|
| EDGG-K | Langen Radar (Kitzingen) - Langen | EDGG_K          | EDGG-K       |
| EDGG   | Langen                            |                 | EDGG         |

The callsign prefix is used to map to the boundary. The field is sometimes empty like in the example above. In this case the ICAO field could be used.

**Comment by albar965** [comment]
> The callsigns can be connected with this API endpoint: https://api.vatsim.net/api/map_data/. Specifically the `VATSpy.dat` file. In it there are two sections `[FIRs]` and `[UIRs]`.

Thanks a lot for your answer. I somehow got lost in the structure.

So I can get a center from [vatsim-data.json](https://data.vatsim.net/v3/vatsim-data.json), the frequencies from [transceivers-data.json](https://data.vatsim.net/v3/transceivers-data.json) and the boundary from [firboundaries.json](https://map.vatsim.net/livedata/firboundaries.json). 

`"callsign": "LZBB_CTR"` from `vatsim-data.json` would translate to `"id": "LZBB"` in `firboundaries.json`, right?

I suppose there is no geometry for TWR and the like and there is not always a boundary for each center. 

What about approach and departure in [traconboundaries.json](https://map.vatsim.net/livedata/traconboundaries.json)? I could not find any matching approach and departure centers in the TRACON boundaries.

**Comment by b-faller** [comment]
> So I can get a center from [vatsim-data.json](https://data.vatsim.net/v3/vatsim-data.json), the frequencies from [transceivers-data.json](https://data.vatsim.net/v3/transceivers-data.json) and the boundary from [firboundaries.json](https://map.vatsim.net/livedata/firboundaries.json).

Yes, although the `VATSpy.dat` sometimes provides an additional mapping (callsign -> boundary ID). So to get the right boundary the process would be: `vatsim-data.json -> VATSpy.dat -> FIRBoundaries.dat/firboundaries.json` I suppose? The boundaries are also provided by the same API endpoint for `VATSpy.dat` (https://api.vatsim.net/api/map_data/) but I don't know what the difference besides the format (.json/.dat) is.

By the way, UIRs are also another thing since they are comprised of FIRs. For example they look like this in `VATSpy.dat`:

```text
EDUU|Rhein Radar|EDGG-D,EDMM-G,EDMM-R,EDGG-B,EDGG-R,EDGG-G,EDMM-Z,EDWW-B
```

Unfortunately I have no idea whether they point to the ICAO field within `[FIRs]` in the same file or directly refer to a boundary ID.

> What about approach and departure in [traconboundaries.json](https://map.vatsim.net/livedata/traconboundaries.json)? I could not find any matching approach and departure centers in the TRACON boundaries.

I did not know about this endpoint but the JSON returned has a prefix field for each item:

![image](https://user-images.githubusercontent.com/12356362/156209092-f1c323fc-2d33-4b6b-8b74-fa60ae9f9a8a.png)

Maybe this is interpreted as a callsign prefix from `vatsim-data.json`?

**Comment by b-faller** [comment]
@albar965 No problem, ping me if you have additional questions. I don't know of any documentation beside the comments in the file itself and the [repository](https://github.com/vatsimnetwork/vatspy-data-project). All I know was more reverse engineering for the demo script I wrote [mentioned above](https://github.com/albar965/littlenavmap/issues/490#issuecomment-702835253) than anything else ...

**Comment by albar965** [comment]
Thanks for the help, all. I implemented the reading of the JSON data now since this is easier to parse. Have to see how many boundaries match.

@Quentin-M One question: Who owns the data or who is the responsible contact? Or is the data free to copy and mirror?

**Comment by albar965** [comment]
![image](https://user-images.githubusercontent.com/15254956/156578893-663059f1-0eb9-4107-ba95-38c9013cacc6.png)

**Comment by albar965** [comment]
Doing ok so far. Not all airspaces resolve.

**Comment by b-faller** [comment]
This is awesome, thank you for your time and work! 

> Not all airspaces resolve.

Do you have some examples which airspaces won't resolve? Maybe I can take a look.

**Comment by albar965** [comment]
> Do you have some examples which airspaces won't resolve? Maybe I can take a look.

Right now based on current [vatsim-data.json](https://data.vatsim.net/v3/vatsim-data.json), [atc_positions.zip](https://github.com/albar965/littlenavmap/files/8190876/atc_positions.zip) at 05.03.22 14:50 UTC:

1. EDGG_NDH_CTR
2. LECM_R2_CTR
3. LFFF_MIL_CTR
4. LIRR_NE_CTR

Seems the suffixes are missing. Not sure if I should do a query without suffix again. How to resolve duplicates then?

Alex

**Comment by b-faller** [comment]
> Right now based on current [vatsim-data.json](https://data.vatsim.net/v3/vatsim-data.json), [atc_positions.zip](https://github.com/albar965/littlenavmap/files/8190876/atc_positions.zip) at 05.03.22 14:50 UTC:
> 
>     1. EDGG_NDH_CTR
> 
>     2. LECM_R2_CTR
> 
>     3. LFFF_MIL_CTR
> 
>     4. LIRR_NE_CTR
> 
> 
> Seems the suffixes are missing. Not sure if I should do a query without suffix again. How to resolve duplicates then?
> 
> Alex

Are those listed callsigns derived from the atc_positions.zip or the actual callsigns that were online from vatsim-data.json?

I briefly checked the content of atc_positions.json for the EDGG example and the middle identifier is wrong for many stations. The [VATSIM wiki page](https://en.wiki.vatsim-germany.org/EDFF_CTR_SOP) lists valid callsigns on the network such as `EDGG_D_CTR` (Dinkelsbühl). If you build the callsign prefix from atc_positions.json with `<center_id>_<middle_identifier>` this station would wrongly be `EDGG_DKB_CTR` and won't match.

Where does atc_positions.json come from? The data at https://api.vatsim.net/api/map_data/ has the correct callsigns.

**Comment by albar965** [comment]
> Where does atc_positions.json come from?

Sorry. Wrong file from IVAO data. It seems like every minute of programming ages my brain for days. :upside_down_face: 

I use these files https://map.vatsim.net/livedata/firboundaries.json
https://map.vatsim.net/livedata/traconboundaries.json for testing.

**Comment by albar965** [comment]
@Quentin-M How often do the files https://map.vatsim.net/livedata/firboundaries.json
https://map.vatsim.net/livedata/traconboundaries.json change? Is it ok for the LNM user to download and install it manually every few days?

BTW: Just made the matching more error tolerant by trying the variants below:
1. `EDGG_DKB_CTR`
2. `EDGG_D_CTR`
3. `EDGG_CTR`

Alex

**Comment by Quentin-M** [comment]
Absolutely no idea as I don't own those services. I will say though that those are all the files that are loaded every time anyone loads https://map.vatsim.net/ in their web browser so it's got a good amount of traffic.. I don't think anybody would even notice the difference your periodic pulling would do in terms of traffic / load.

**Comment by albar965** [comment]
Ok. Thanks. I'll contact them.

**Comment by b-faller** [comment]
> BTW: Just made the matching more error tolerant by trying the variants below:
> 
>     1. `EDGG_DKB_CTR`
> 
>     2. `EDGG_D_CTR`
> 
>     3. `EDGG_CTR`

Great so the `DKB` that did not resolve was IVAO only? If I search both JSONs ([firboundaries.json](https://map.vatsim.net/livedata/firboundaries.json)/[traconboundaries.json](https://map.vatsim.net/livedata/traconboundaries.json)) I don't find `DKB` or other middle sections you said were not matched.

Does the current implementation of fuzzy matching support extensions such as `_1` or 2,3,... as in `EDDS_TWR` to `EDDS_1_TWR` which is sometimes used during shift changes to work around the fact that connected ATC callsigns must be unique? I've seen multiple underscores being used as well e.g. `EDGG_K__CTR`.

**Comment by Gulliver54** [comment]
Hi Alex,

Great stuf. 
Downloaded IVAO ATC boundaries and they seem to work.
Thanks.

![afbeelding](https://user-images.githubusercontent.com/33782220/163795978-ea763ba2-1631-4ec1-b027-dcb8f06b7909.png)

**Comment by Gulliver54** [comment]
Hi Alex,
Although the file is loaded inside Folder "user airspaces", only unticking "online airspaces" will disable these boundaries. 

![afbeelding](https://user-images.githubusercontent.com/33782220/163798185-05a6d700-a004-4d72-8779-a83d254c435e.png)

**Comment by albar965** [comment]
> Hi Alex,
> Although the file is loaded inside Folder "user airspaces", only unticking "online airspaces" will disable these boundaries.
> No big deal, and thinking about it, most likely these boundaries will belong to the online airspaces.

Internally they are treated as online airspaces. I think this is ok to put them into the online category.

**Comment by vapouryh** [comment]
Hi there, 
I've had a thorough look throughout the thread and have got LNM to the point where it can pretty much all of europe's online vatsim airpsaces for centers and approach/departures. I get that tower and ground don't have any sort of boundaries and that's fine, the only two things I have issues with is getting US approach and departure boundaries to show as well as EUROCONTROL boundaries and also showing RSTR areas on the map. With the RSTR, it will show up using the Simulator airspace library but then inteferes with my online boundaries... this isn't such a big issue though so i'm not that bothered if it's something hard to fix.
Many Thanks.

**Comment by albar965** [comment]
> With the RSTR, it will show up using the Simulator airspace library but then inteferes with my online boundaries... this isn't such a big issue though so i'm not that bothered if it's something hard to fix.

Sorry, but I have no idea how to remove the duplicates or merge the different airspaces.

**Comment by vapouryh** [comment]
> > With the RSTR, it will show up using the Simulator airspace library but then inteferes with my online boundaries... this isn't such a big issue though so i'm not that bothered if it's something hard to fix.
> 
> Sorry, but I have no idea how to remove the duplicates or merge the different airspaces.

Any idea on how to get the boundaries for USA approach/departures though?

**Comment by albar965** [comment]
> Any idea on how to get the boundaries for USA approach/departures though?

You can try https://www.openaip.net/

**Comment by vapouryh** [comment]
> 

Thanks for the reply, after having used the traconboundaries.json I now get all of them show up in the US. Cheers.

**Comment by maszat** [comment]
@vapouryh would you please share a little more details. I have firboundaries and traconboundaries in the user airspaces folder, but that itself did not resolve the US approach/deparure display ( still only circles ) and some ( not all ) US centers are also still only circles.
Probably important to mention that under the menu item "Airspace Libraries" I only selected "Online". The reason for that is that if I select "User" also, then it does display more centers and of course more accurately outlined, but that defeats the purpose since those may not be online. 
I try to mimic the behavior of how the SimAware website displays centers/approach - that website somehow does a very good job.
Any help appreciated, pilots. Thanks and regards.

**Comment by albar965** [comment]
See last chapter `Online Airspaces` here: https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/AIRSPACELOAD.html

The callsign approach does not work for all airspaces. A lot remain circles, unfortunately.

Where is the id stored? Do you have an example file?

The problem is that LNM tries to match airspaces for VATSIM and IVAO which come in different flavors.

**Comment by albar965** [comment]
Ok. Will have a look at this.

**Comment by maszat** [comment]
Alex, happy new year,
I revisited this topic with the latest 3.0.1, imported the traconboundaries.json and firboundaries.json, and it seems to have loaded perfectly, the screenshot shows that all the approach boundaries look pretty good.
I think this is now just a matter of a little magic of yours to do the fuzzy name matching for the VATSIM online approach/departure controllers. 
thank you

![image](https://github.com/albar965/littlenavmap/assets/113255/4ae00be2-50b7-4240-bedc-0477f86941f6)

**Comment by albar965** [comment]
> Alex, happy new year, I revisited this topic with the latest 3.0.1, imported the traconboundaries.json and firboundaries.json, and it seems to have loaded perfectly, the screenshot shows that all the approach boundaries look pretty good. I think this is now just a matter of a little magic of yours to do the fuzzy name matching for the VATSIM online approach/departure controllers. thank you
> 

A Happy New Year to you too!

I'll have a look at this. Maybe can sneak it into 3.0.2.beta but no promises.

Alex

**Comment by albar965** [comment]
Now ignoring the middle suffix like the `O` in `EDMM_O_CTR` when looking for airspaces. Looking better but still not complete. Using https://map.vatsim.net/livedata/firboundaries.json and https://map.vatsim.net/livedata/traconboundaries.json in the screenshot below:

![grafik](https://github.com/albar965/littlenavmap/assets/15254956/e1e762e3-89d2-487b-a6e1-1915b39641a5)

**Comment by maszat** [comment]
very nice. Europe (for some reason) has always looked better, even in the earlier version, I will check with US departures and centers (when 3.0.2 comes out). Thank you for the effort!

**Comment by albar965** [comment]
Yep. It's more sparse in the US.
I also tried the files from the SimAware TRACON Project but this has less boundaries and less matches.

**Comment by maszat** [comment]
understand, currently I can't imagine a scenario where that logic will not help.

**Comment by maszat** [comment]
thank you for 3.0.2, Alex! First test results (it is possible that I do something wrong)

A90_APP (Boston Approach) looked great
NY_APP did not resolve - when I look at the json file, it may be beacuse the ID is N90 and the value of the "prefix" parameter is "NY", whereas in Boston both ID and Prefix were set to A90 in the json
BOS_CTR did not resolve - this is NOT becasue of the code, this is a data mismatch. Howere, I edited the firboundaries file and manually replaced KZWB with BOS, took 2 seconds and I honestly did not mind doing that for the centers where I fly and care about

best
Kornel

**Comment by albar965** [comment]
Thanks for the feedback. I'll have a look at it for the 3.0.X releases.

**Comment by albar965** [comment]
I cannot find a better match than prefix/suffix. The information is really missing.

**Comment by maszat** [comment]
I'm sorry if you feel that way, my above screenshot and explanation showed that you are very close. I wish I could explain it better, not sure if this forum post does justice to that.
1. the fact that your code looked for "ID" and not "prefix" (these are JSON file parameters) when matching approach boundaries looks trivial
2. the fact that people need to make some manual data edits for centers (and that is extremely easy) is trivial
3. the flexibility in the program to allow a few other suffixes such as "FSS" (see my above post for them) also seems to be trivial
The combination of these 3 yields a perfect solution with minimal one time data edit by the user.
I can live with the current ~85% solution happily, but it's a shame not to round it up :)
Respect, don't take any of this as negativity!

**Comment by albar965** [comment]
Sorry, but I don't understand. A few other suffixes? Which ones and these should match to what?
Examples might help.

**Comment by maszat** [comment]
Alex, allow me please to send you an email with all the details, I will provide a very detailed explanation of all. If you prefer to email me first, you can reach me at lnm at mezo dot com and I reply back.

**Comment by albar965** [comment]
Here is my contact email: https://albar965.github.io/contact.html 

Alex

**Comment by maszat** [comment]
thank you, detailed email sent

**Comment by albar965** [comment]
Thank you got it. Will get back to you but give me a day or two.

**Comment by maszat** [comment]
NO RUSH whatsoever, if I need to clarify any bullet points of bring more examples, happy to !
