### ISSUE TITLE
Export for VPilot

### ISSUE THREAD

**Issue by nmeier** [albar965/littlenavmap#493]
I'm exporting my flight plans to vPilot for loading into X-Pilot. Somehow I managed to blank out the Voice type field

![image](https://user-images.githubusercontent.com/312857/75119530-a3488500-5651-11ea-917e-9db1a4559d6c.png)

I then succeeded to save the flight plan but X-Pilot balks at the missing attribute value.

![image](https://user-images.githubusercontent.com/312857/75119541-c115ea00-5651-11ea-814b-f41931ff275f.png)

Adding Full to this attribute fixes the situation

`VoiceType="Full"`

I've reported this to the XPilot devs in their forum, as I think that flightplan should still be load-able.

I'd suggest though to change the exportFlighplanAsVfp to set an explicit **default** value of **Full** when no value is set. I realize the UI doesn't have flight plan format specific fields, otherwise one could use radio boxes, or add validation.

https://github.com/albar965/littlenavmap/blob/f36909f79f5cc31cdede0f794fa90bd5e07dc8bb/src/route/routeexport.cpp#L1166

**Comment by albar965** [comment]
@nmeier Thanks for the investigation. Very helpful. I can pre-fill the field with `Full`. That  could also fix it.
I'd like to add selection boxes for predefined values instead of these free text boxes. But it's a bit difficult to get to the allowed values for each client. Therefore, free text.
Alex
