### ISSUE TITLE
Only Approach procedures available with MSFS2020 scenery library

### ISSUE THREAD

**Issue by petertrotman** [albar965/littlenavmap#555]
As title - showing procedures for any airport with the MSFS2020 database selected will only show Approach procedures - no Departure or Arrival procedures are available even though they do exist in the sim. If I switch to my Navigraph database then they all work as expected - this problem only occurs if I turn Navigraph features to off and select the MSFS2020 scenery library.

Using 2.6.0 Beta and I have fully loaded the MSFS2020 scenery database.

**Comment by albar965** [comment]
Known issue. See changelog. 
I'd really like to fix this myself but the BGL file format is not open and I cannot read the SID/STAR parts so far.

Maybe future updates of the SDK allow me to create SID/STAR. Currently this is not even supported in the SDK.

I can only recommend to use the Navigraph database anyway (not affiliated with them) since the MSFS navdata format has too many limitations.

Anyway, will try to fix this in future updates.

**Comment by petertrotman** [comment]
Thank you. Yes you are not the only one with complaints about the current state of the SDK!

What should I recommend to people who only have MSFS in order to get full functionality of the procedures? Is a Navigraph subscription the only way? (assume they don't already have x-plane).

**Comment by albar965** [comment]
> What should I recommend to people who only have MSFS in order to get full functionality of the procedures? Is a Navigraph subscription the only way? (assume they don't already have x-plane).

Use the included older Navigraph database or get a subscription. As far as I can see even the older 1801 database has more procedures than the MSFS one. But this is just my impression. Not measured.

**Comment by bymaximus** [comment]
Hello @albar965, does reading bgl files into xml and reading those xml to store sid/star data solve the problem for now?

Szpike User from fsdeveloper created this tool which exports bgl data into xml, this xml seems contains sid/star data. Maybe use this for now? Just a sugestion if you didnt known about this tool.

[MsfsBglXml](https://www.fsdeveloper.com/forum/threads/msfsbglxml-convert-msfs-2020-bgl-files-to-xml.450677/) 

[Bgl msfs2020 format?](https://www.fsdeveloper.com/wiki/index.php/FS20_BGL_File_Format)

**Comment by albar965** [comment]
Using external tools is not doable in the loading process.

But this will help for sure:
https://www.fsdeveloper.com/wiki/index.php/FS20_BGL_File_Format

**Comment by icykoneko** [comment]
I'd like to take a stab at implementing this.  I used that wiki to create a template in 010 editor to visualize the SID/STAR records and it looks good so far.  I don't know if it will affect exporting; I was going to try having it produce the same rows found in the built-in Navigraph database.

**Comment by albar965** [comment]
@icykoneko All help is welcome! Especially since other tasks and bugs (I also have an internal list) are stacking up for the next release.

Send me an email if you have questions. You have to use the `release/3.6` in atools since `master` is unstable development and most likely old. Also use the [Navdatareader](https://github.com/albar965/navdatareader) for testing and debugging. This is much simpler to build and run than the whole LNM.

Database schema is brielfy described in the `create_*.sql` files [here](https://github.com/albar965/atools/tree/release/3.6/resources/sql/fs/db).

Starting points are https://github.com/albar965/atools/blob/release/3.6/src/fs/bgl/ap/approach.h for all procedures and https://github.com/albar965/atools/blob/release/3.6/src/fs/bgl/ap/transition.h for transitions.

The two above classes read from BGL while https://github.com/albar965/atools/blob/master/src/fs/db/ap/approachwriter.h, https://github.com/albar965/atools/blob/master/src/fs/db/ap/approachlegwriter.h, https://github.com/albar965/atools/blob/master/src/fs/db/ap/transitionlegwriter.h and https://github.com/albar965/atools/blob/master/src/fs/db/ap/transitionwriter.h take care of writing the objects read from BGL to the database.

One more difficulty are common routes where parts of several SID and STAR are stored in a separate structure and have to be merged into the SID and STAR. I have code for this but this is a part of the X-Plane and Navigraph compiler.

**Comment by icykoneko** [comment]
https://github.com/albar965/atools/pull/11 :)

**Comment by albar965** [comment]
Ticket for RF legs submitted: #103367

Apart from RF I see no issues with the procedures. Good job! 

@icykoneko : I'd like to read the MSFS POI BGL files and import them into the LNM userpoints. If you're interested we can cook something up.
