### ISSUE TITLE
No Magnectic Declination

### ISSUE THREAD

**Issue by Gfurst** [albar965/littlenavmap#564]
Using Little Navmap, alongside X-Plane 11.50

So something that still drives me nuts is figuring out proper heading/course/radial, because most often than not, it just wont match with what I see in-game, with a very wide margin of error. I fly in South America, ha donly the stable version until today, when I updated to the beta to try it out, and still had the confusion.
So I'm gonna use the very fresh example from today's flight:
![Screenshot_20200924_190640](https://user-images.githubusercontent.com/12454141/94205184-1db3de80-fe99-11ea-9db4-8f9f8c637264.jpeg)
From SDCA to SBMT, with a little use of a navaid, the vordme STN, so I would just veer off a bit from the runway until I catch the desired radial and follow it. In my flightplan, for that leg it says `Course °M=70|Course °T=71`, however taking the measure tool, with origin from the VOR I'm getting `271°M/250°T`, but reversed, if you subtract 180° you then get 91°M, which was in fact the course had to follow for this flight (after some very confused veering wildly off course). 
The funny thing is, I already have `ignore declination of VOR`in options checked, assuming that the VOR data would be old, however as it turns out, the VOR data is the only one correct in this thing, because I'm fairly sure this whole region has in general a declination from 18~22°, but it never shows up in my plans, it doesn't really matter when follow the gps, but the heading I get from the compass never matches with flight plan. So I can only conclude its the overall declination data/source that is erroneous.

**Comment by albar965** [comment]
Try to reload the scenery library. I've got reports of wrong declination (it is calculated for X-Plane opposed to the other simulators where it is read from the scenery).
I could reproduce this only once. After reloading it was gone. :-(

**Comment by albar965** [comment]
Can confirm and reproduce now.

**Comment by Gfurst** [comment]
So how does this work specifically? How does X-plane handle it and where does Navmap get its info? I'd imagine it must be something like the global winds file.

**Comment by albar965** [comment]
For simulators having a `magdec.bgl` the table is loaded from there. This is FSX, P3D and MSFS.

X-Plane does not provide magnetic declination tables but instead uses the [World Magnetic Model](https://en.wikipedia.org/wiki/World_Magnetic_Model). This is a C code library which comes with a table of coefficients that allow to calculate the declination for any point on earth at any (within reason) time. 
LNM uses this code to calculate the declination in one degree steps and stores it in the scenery database when loading from X-Plane. The current year and month is used to calculate the declination. This is only done when loading the scenery library since it is too CPU intensive to do it on the fly.
This is what is shown in LNM for airports, waypoints and when you hover the mouse over the map.
VOR and ILS come with their own declination values which might differ from the actual value around since they might be calibrated years (VOR sometimes decades ago). Therefore, the differences between VOR and surrounding (mouse hover or airport).

Our special issue (Brazil and Germany) was that the WMM code was locale dependent and expected a comma as decimal separator. But the numbers were stored with a period American style. The bug might also be Linux related because I could not reproduce it in Windows.

Anyway, fixed, closed, done for 2.6.1.beta.
And thank you for reporting!
