### ISSUE TITLE
Dark UI theme using Linux not available?

### ISSUE THREAD

**Issue by satscape** [albar965/littlenavmap#567]
I'm using Linux (Debian-testing) and X-Plane 11.5x - I noticed a screenshot showing a dark theme, but the bit in the settings where you choose the theme doesn't have that option, the only one I can find is the map theme chooser which does go dark, but **not** the rest of the UI. I have a dark system theme (XFCE), and also set Qt apps to use a dark theme and other Qt apps do conform to this setting. Is the theme switching not working on Linux yet? If so, I'll wait, but if there is something I'm missing, please let me know. Here's a [screenshot](https://imgur.com/a/XHKljng) to illustrate.
Many thanks for an awesome app!

**Comment by albar965** [comment]
Hi,
If you're looking for a dark mode in LNM: `Window` -> `Style` -> `Night`

I'm afraid that there is no simple solution. I'm using Kubuntu for development and LNM also does not adhere to the style either. 

It's because I'm not using the system supplied Qt libraries but generic one from Qt.io to allow running LNM on more than distro.
Alex

**Comment by satscape** [comment]
Thanks Alex, that Night mode is just what I was looking for, many thanks and keep up the good work!
