### ISSUE TITLE
Strange merge performance fuel flow value from MSFS2020

### ISSUE THREAD

**Issue by Wnthr** [albar965/littlenavmap#586]
* Include your OS and version in detail: `Windows 10 64 bit`
* Flight simulator and version like: `Microsoft Flight Simulator 2020`
* AIRAC cycle and navdata source if applicable: `Navigraph Airac Cycle 1801`

When trying to merge performance data from MSFS2020, the numbers seem wildly wrong. I flew yesterday for over 4 hours, and today for almost 3, but the despite the average fuel flow according to the logs are around 825 pph, the merge performance dialog believes that the fuel flow in cruise is more than 3 times that value, at about 2800 pph.

<img width="622" alt="logbook" src="https://user-images.githubusercontent.com/14862505/97748620-0b5b3f00-1aee-11eb-89f2-47c45b43ce24.png">

<img width="485" alt="merge" src="https://user-images.githubusercontent.com/14862505/97748655-19a95b00-1aee-11eb-9854-810847206dee.png">

None of the flights were time warped. Maybe some value conversion thing going on?

**Comment by Wnthr** [comment]
Some more data:

It seems that the fuel value in the plane matches the info in the current performance window during climb, after that, when switching to cruise, the current performance value spikes, while the plane data goes down. Pictures from roughly the same moment. Also, the TAS value seems to differ a little bit, not sure why that's happening either, but the diff is small enough that it doesn't seem to be a big thing either way.

<img width="1920" alt="fuel_mgmt_in_plane" src="https://user-images.githubusercontent.com/14862505/97759503-7c582200-1b01-11eb-9591-6bd1a87f3cc8.png">

<img width="411" alt="current_performance" src="https://user-images.githubusercontent.com/14862505/97759509-7e21e580-1b01-11eb-8cd6-0a380068b455.png">

**Comment by albar965** [comment]
Some add-ons or mods "doctor" the fuel flow due to simulator limitations. This happens quite often in MSFS unfortunately. Check if the fuel flow in the performance tab of LNM matches what is shown in the aircraft.

**Comment by Wnthr** [comment]
I don't understand what you mean by 'in the aircraft', the above screenshot is the only indication inside the aircraft of the fuel consumption that I know how to access. Regardless of the display, the aircraft seems to spend the fuel inside the tank of the aircraft at a rate which makes is predictable, I assumed LNM would use the difference in fuel remaining in the tank over time to calculate the average, but apparently that's not what's going on then?

**Comment by albar965** [comment]
> I don't understand what you mean by 'in the aircraft', the above screenshot is the only indication inside the aircraft of the fuel consumption that I know how to access.

The aircraft should have a fuel flow indication like pounds per hour or similar. Otherwise it is incomplete.

LNM looks at the current fuel flow given by SimConnect. Therefore, you can time warp and move your aircraft to TOD without issues as mentioned in the manual. This is working without problems for all FSX, XP, P3D, most add-on and stock MSFS aircraft.

I cannot do much about mods where an aircraft gives a wrong fuel flow indication that does not match the fuel consumption from the tanks. Like giving a fuel flow indication of 250 pph through SimConnect and emptying the tanks for 500 lbs after an hour flight, for example. This usually happens if add-on developes try to work around limitations in the simulator.

I'd suggest to contact the author of the mod.
