### ISSUE TITLE
Running LIttle Navmap 2.6.6 with MS 2020 is crashing the sim.

### ISSUE THREAD

**Issue by kenord** [albar965/littlenavmap#603]
I tend to start Little Navmap (v2.6.6) before starting FS2020 and until the recent FS update it's been fine. Since the update to FS2020 1.12.13.0 the sim is crashing to the desktop with Navmap running. If I start the sim and get flying and then start Navmap then I get a CTD immediately. I guess is something broken in FS2020 and not Navmap's fault, either way, I can't use Navmap which is a huge shame cos it's fantastic.

**Comment by albar965** [comment]
This is a known issue. Please report this to Asobo since their update introduced the bug. I cannot do much about this. This code in LNM did not change for a long time and is still working with FSX and P3D.

The bug appears randomly. For some it happens only with the bush flying missions other have no problems at all.

You can vote for the issue here:
https://forums.flightsimulator.com/t/little-nav-map-problem-since-dec-22-update/340065

**Comment by carfesh** [comment]
Sadly the moderators have closed several posts related to this issue already, as they say that the issue discussion forum is for MSFS issues only, not 3rd party issues. I'm curious to see what will happen; probably not much when I look at the lists of issues they repeatedly show.  I would believe that the crash of the sim is an issue, but some claim otherwise. For instance this discussion here was just closed: https://forums.flightsimulator.com/t/3-ctds-atfer-the-latest-update/338623/47

**Comment by kenord** [comment]
Thanks. I've raised a Zendesk ticket. I do realise that the problem has to be for them to correct. I hope they fix it soon cos I love flying with Navmap.

**Comment by carfesh** [comment]
Same for me! :) And while it certainly feels like cheating during the bush trips, I' still learning and LNM is helping me a large deal to actually get from A to B.. besides that, I also love the LNM logbook, while I have already lost my in-game logbook twice.

**Comment by albar965** [comment]
I submitted a ticket. They review the information. We'll see. Hope they/we get this fixed somehow.
I can reproduce this during the bush trips only. Normal flights are not affected. No AI settings in simulator or LNM help. MSFS dies without sending a SimConnect error.

**Comment by kenord** [comment]
I got a plausible suggestion from the FS2020 forums that turning off fetching AI and multiplayer aircraft and ships in LNM might solve the crashes. See the Tool menu and the first item. I'm trying it and no CTD so far (fingers crossed).
![image](https://user-images.githubusercontent.com/5802873/103227659-cce3d400-4926-11eb-9f71-f6aa1b4ff0b1.png)

**Comment by carfesh** [comment]
Don't know what I'm doing differently, I've tried that and also disabled "Connect automatically", and it still crashes for me once I connect it manually.

**Comment by albar965** [comment]
BTW: In case sombody misses the obvious: You can still use LNM as a flight planner and a static map and stay disconnected.

**Comment by kenord** [comment]
> 
> 
> Don't know what I'm doing differently, I've tried that and also disabled "Connect automatically", and it still crashes for me once I connect it manually.

**Comment by carfesh** [comment]
So for the record, I've opened a Zendesk issue for this as well, and received the following reply: "Apparently there's an issue with Simconnect across all platforms (not only Microsoft Flight Simulator).

We are currently investigating this issue. In the meantime, we would recommend to disable Simconnect."

Not sure what exactly this means, hopefully they will still come up with an actual solution.

**Comment by carfesh** [comment]
BTW: when I load the Nevada flight plan, and connect a free flight, LNM will also cause this crash. So the reason it mostly occurs during bush trips is because you usually load that plan. It has something to do with the flight plan, which I think it interesting at least.
