### ISSUE TITLE
Customized departure/arrival procedures

### ISSUE THREAD

**Issue by icykoneko** [albar965/littlenavmap#615]
This may be similar to #576 but I'm looking for an easier way to automatically input a procedural turn to heading, especially when departing, but also when arriving.  Currently, I do this by hand, but it'd be nice if the distances could be better aligned to the performance data.

For example, so I want to depart on runway heading 40 deg due to high surface winds, but my destination is bearing 210 deg.  I'd like some way to insert a "custom departure" via waypoints at least to plot the turn.  I would think this feature should allow for some flexibility, such as starting from a specified location (as opposed to just begin turn n NM after departing, although that would be nice to have as well).  The number of waypoints used might be customizable as well.  I would imagine by default, one per 30 or 45 deg (again, since it's not a pre-programmed procedural turn).

Here's an example of what I currently do manually.  In this case, I seemed to be pretty accurate, but I find myself repeatedly having to plot these and wish it was automated.  Thank you in advance :)

![custom_departure_example](https://user-images.githubusercontent.com/28579746/107891299-a506fa80-6eeb-11eb-8772-338a967b9d8f.png)

**Comment by albar965** [comment]
I might add a simple custom departure procedure similar to the approach but this will never be aligned with the performance data since LNM does not know the aircrafts turn radius and speed.

I fail to see the user case anyway. Normally depart the airport in whatever direction and then join the first flight plan leg. 
For VFR this is not needed and for IFR you have to use real procedures anyway.

**Comment by albar965** [comment]
No answer. Closing.
