### ISSUE TITLE
Possible bug in Information Window

### ISSUE THREAD

**Issue by PaulFWatts** [albar965/littlenavmap#64]
When accessing an airport on a new flight plan the "Nav Aids" Tab is showing a Nav Aid from an airport on a previous Flight Plan and not the Nav Aids for the currently selected Airport (see screenshots)
![screen shot 2016-11-07 at 8 59 47 pm](https://cloud.githubusercontent.com/assets/7057417/20055554/6270edde-a52d-11e6-9bc7-ca476af0c34b.png)
![screen shot 2016-11-07 at 9 00 06 pm](https://cloud.githubusercontent.com/assets/7057417/20055559/6a369b2c-a52d-11e6-87ad-1371954460da.png)

**Comment by albar965** [comment]
Navaids are not always connected to an airport. Only NDB and waypoints have this connection as you can find out in the Navaid search tab (trick: use "-" as search term to find not empty airport idents).

So what is added to the info tabs depends entirely what is nearby the mouse click. All tabs are always filled with everything nearby the click. Even if they are not raised. The navaid tab might receive multiple entries. The airport tab not.

So if you click on an airport that has a VOR nearby, both will be loaded into the tabs. No tab is raised in this case but you can select the navaid tab and you will see the VOR.

If you continue with the situation above and click on an airport with no navaid nearby, the airport tab will be raised since it is the only object nearby click. The VOR info stays in its tab since it might be useful for later.

**Comment by albar965** [comment]
Closing since it is clear now. Reopen if any bugs appear.
