### ISSUE TITLE
GLS approaches

### ISSUE THREAD

**Issue by borgdylan** [albar965/littlenavmap#640]
ToLiss have recently added GLS, LOC B/C, LDA and IGS approaches to their A319. I tried to load approaches for airports that are known to have GLS approaches such as EDDF and LEMG. LittleNavMap did not list those. Are these supported in LittleNavMap?

**Comment by albar965** [comment]
GBAS/GLS and the stations are currently missing in LNM. This is a bigger task.

**Comment by albar965** [comment]
Approaches are already provided in LNM. Examples:
GLS approach: Bremen (EDDW) Approach GNSS-Y 27 DW010 
IGS approach: Aosta (LIMW) Approach IGS 27 FG27

Missing:

- [ ] ILS/MLS/GLS Category in table `ils`
- [ ] Need to add and declare type of GLS in table `ils` plus additional fields
- [ ] Display of channel/frequency of above types in LNM in information, tooltips, runway info and flight plan table. No use to show on map since station coordinates are not related to runway threshold
- [ ] Display of more details for approaches

Currently not read:
- 14 FRAP, Final Approach Course Alignment point of SBAS or GBAS path point, `SBAS_GBAS_FINAL`. X-Plane.
- 15 GLS, Ground station of differential GPS used for GLS approaches, `GBAS`.  X-Plane and DSF.
- 16 LTP/FTP, Landing threshold point or fictitious threshold point of GBAS or SBAS path point, `SBAS_GBAS_TRESHOLD`. X-Plane.
