### ISSUE TITLE
X-Plane FMS export errors with 2.6.15

### ISSUE THREAD

**Issue by ahuimanu** [albar965/littlenavmap#741]
The X-Plane 11 FMS format is incorrectly exported.  The documentation for the FMS format is discussed here: https://developer.x-plane.com/article/flightplan-files-v11-fms-file-format/

It would seem that it is necessary to include A as the first letter for an airport departure or arrival. 

2.6.15 is writing FMS plans without this.  This causes errors with other tools, such as HiFi's ASXP, which is unable to parse the file with this error.

This is correctable by hand, but seems to be a bug in any case.

**Comment by albar965** [comment]
I'm very well aware of the FMS 11 article and I'm also well aware about the corner cases not mentioned there.

After experimenting with internal and official ids I found that X-Plane has an inconsistent behavior regarding its internal, ICAO, FAA and local ids used with either procedures or not. I found the best results using ADES and ADEP only for airports if a procedure is used. On the other hand ADES and ADEP can always be used int the waypoint list but not in the departure and destination on top of the file.

I'd rather report this to HiFi since X-Plane deals without issues with these.

**Comment by ahuimanu** [comment]
I've reported it there as well.  Their XP product hasn't changed since November of 2020 (at least in public releases), so it would seem to be a new behavior in 2.6.15 of LNM.  So, the A is not there if a departure isn't selected?  Can I improve results by including a departure?  I raised it as an issue as this is new behavior in LMN.  I raised the issue as I know the changelog introduced some XP-specific changes and perhaps thought this might have been an oversight.

**Comment by albar965** [comment]
I changed the FMS export for 2.6.15. 

I tested all kind of obscure combinations (`X...` airports and others) with procedures and not. At least X-Plane is loading them fine in the GPS.

I'll have a look at this again. Can you give me a few examples where it does not work and the corrected ones? You can attach the files here if you rename them to .txt

**Comment by albar965** [comment]
I see what's going on there. Does not even work properly in the X-Plane FMS. :frowning_face: 
I'll probably release a hotfix for this.

**Comment by albar965** [comment]
Special cases which do not work with ADEP/ADES despite being airports:
`UMIO`/`XUM0003` to `UMMI`/`XUM0004` (both have ICAO different from ident)
`LCL`/`XAY000B` to `AU999`/`XY000G` (both have a local code different from ident)
Neither id works in a flight plan with ADEP/ADES.  ¯\\\_(ツ)_/¯

**Comment by ahuimanu** [comment]
I wonder if filing a bug report at X-plane is a good next step?  They too released a significant number of scenery changes for 11.55.  It seems that the majority of cases prefer the "A" prefix?  

I tried to find the issue myself and looked here, but I don't think I looked in the right place: https://github.com/albar965/littlenavmap/blob/master/src/routeexport/routeexport.cpp

**Comment by albar965** [comment]
I introduced the issue in `FlightplanIO::saveFMSInternal` as well as in `Route::adjustedToOptions`. You have to look at the branch `release/2.6`.

Maybe I have to use DEP/DES for all airports which have an ident longer than four characters. I have to do more tests.

Filing a bug report: I can do this. I already have a bunch of examples.

**Comment by albar965** [comment]
Some more research:

1. This affects all airport having a long X-Plane ident. They have to be saved using DEP/DES. Not a big issue since these do not use procedures and are most likely not used in a FMC. GPS loads these fine.
2. But it also affects airports having an internal id different from ICAO (e.g. KIYA and KEOE). Some of these have procedures. Above workaround cannot be applied here. This is worst.

It does not matter if you use the internal X-Plane id, ICAO or FAA id for the cases above. Loading will fail with ADEP/ADES.
Codes in the waypoint list do not matter. These are always accepted.

Here are a few plans with variations which do not load:
[FMS plans not loading.zip](https://github.com/albar965/littlenavmap/files/6903068/FMS.plans.not.loading.zip)

**Comment by albar965** [comment]
Question: Can ASXP load FMS3? Maybe this is a temporary workaround.

**Comment by albar965** [comment]
Bug report sent.

**Comment by albar965** [comment]
BTW: In some cases it helps to truncate the long airport idents to six characters. For example in the file `XEN0008-ENSD not loading.fms`.

**Comment by ahuimanu** [comment]
I think your commit with this note "Correct X-Plane FMS export to always use ADEP/ADES for airports." will likely fix 99% of the cases

**Comment by albar965** [comment]
Here is a build with these changes from the log messages above. Version is still 2.6.15 but the revision differs which you can see in the about dialog:
https://www.magentacloud.de/lnk/GJrAggxK

X-Plane behavior is a bit strange when loading plans. Last commit message describes it. The sim refuses to load a FMS if ICAO is present and X-Plane ident is not equal to ICAO, for example.

**Comment by ahuimanu** [comment]
ASXP happily loads this now.  I believe it is accounting to the inclusion of the "A" as a part of DEP and DES.

**Comment by albar965** [comment]
> ASXP happily loads this now. I believe it is accounting to the inclusion of the "A" as a part of DEP and DES.

Thank you for the feedback! Very helpful.

The DEP/DES is exactly what ASX and probably other tools do not like.
It is not mentioned in the official blog post on x-plane.com but one of the XP devs explained in the x.org forum that DEP/DES is required to load these airports with special ids.
These are the nerve wrecking corner cases not mentioned in the blog post.

Out of 37000 airports are 1100 which require DEP/DES which will cause issues with ASXP.
15 out of the 1100 have procedures which cannot be used as a result. This is negligible IMO.

Let me know if you run into any issues.

Alex
