### ISSUE TITLE
Load scenery asynchronously

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#750]
Should not require a big effort since scenery is compiled into a separate database anyway

**Comment by cowreth** [comment]
Hi Alex,

May I jump on that one to propose an other angle ?
Yes, I'd love to see an asynchronous refresh.

I may also love to have a way to only refresh the community files. Because I often change my community folder between flight (including / excluding aircraft or sceneries). But my "core" isn't that much updated.

That could be hard to implement though, because I expect you to drop the db and do everything in a certain order and introducing a "partial refresh" may also introduce bugs.

Just wanted to let you know that this would be appreciated, though :)

Cheers !
K.

**Comment by albar965** [comment]
> Yes, I'd love to see an asynchronous refresh.

This is doable since the compilation has a temporary database as a target anyway. Still might cause unexpected issues.

> I may also love to have a way to only refresh the community files. Because I often change my community folder between flight (including / excluding aircraft or sceneries). But my "core" isn't that much updated.
> 
> That could be hard to implement though, because I expect you to drop the db and do everything in a certain order and introducing a "partial refresh" may also introduce bugs.

MSFS Community folder and add-ons for other sims? Sorry, but partial refresh is close to undoable due to the many relations between airports, navaids and whatnot.

**Comment by cowreth** [comment]
> Sorry, but partial refresh is close to undoable due to the many relations between airports, navaids and whatnot

Ahah, totally expected - and understood ;)

**Comment by cowreth** [comment]
> MSFS Community folder and add-ons for other sims ?

Hehe, only refreshing MSFS Community. Nothing for the other sims.
Use case : before each flight, I select / deselect add-ons. Or update them. Or install new ones. That occurs nearly each every day. And each every day, I have to rescan the entire library, including the ASOBO one. Which doesn't move quite often :).

Hence the feature request : would it be possible to refresh only a directory ? Remove a directory from the SQLite db, without rescanning ?

**Comment by albar965** [comment]
> Hence the feature request : would it be possible to refresh only a directory ? Remove a directory from the SQLite db, without rescanning ?

Sorry, nope. Too many relations. It's already a pain with the FSX/P3D/MSFS airport update system.

Why not enable all scenery, load it into LNM and then enable/disable scenery as you need for flying in the sim without updating LNM? In worst case you'll see an airport in LNM which is not in the sim.

**Comment by cowreth** [comment]
Your answer makes total sense, thanks for taking the time.

May I jump on your proposition and make a new request then ? 

The proposition is good, and I used to do that at the beginning. But now I can't because if I download / update a scenery, I then have to put back everything _then_ remove everything for the scan, so that the new one is taken in account without all others being removed.

May I jump on that for a different request then ? 
Can we have an option where to add a personal folder other than the Community one ?
Then I'd be able to store all my sceneries in a folder, then only enable the ones I want in the Community one.

Option : LNM to ignore "links" in the Community folder. I use tools (like Addon Linker), in a very standard setup where all my addons are stored in a directory but only the ones I'm using are _linked_ in the community. If LNM doesn't ignore links (or at least, links leading to subfolders of the "custom cirectory"), then it will count twice each every addon. Which is no big deal ;)

**Comment by albar965** [comment]
> Can we have an option where to add a personal folder other than the Community one ?

#296 proposes this but is more far future.

> LNM to ignore "links" in the Community folder. I use tools (like Addon Linker), in a very standard setup where all my addons are stored in a directory but only the ones I'm using are _linked_ in the community.

A bit difficult since there can be links everywhere in a path. This is normally transparent to the program.

**Comment by albar965** [comment]
Fixed with d0fe68ae8b0d3c110deee907b411cad92c906ef9
