### ISSUE TITLE
Bad display of the map

### ISSUE THREAD

**Issue by pacha35** [albar965/littlenavmap#811]
Hi,
sometimes, when I zoom on the map, Ihave a large black square on a part of the map.
My version of LNM is 2.6.17

Regards

zoom 1 OK
![_LNM_bug1](https://user-images.githubusercontent.com/46076619/140646947-ba4e1fea-fe14-482e-ac52-ac3ba6d1de4e.jpg)

zoom 2 bad
![_LNM_bug](https://user-images.githubusercontent.com/46076619/140646968-b0f9e9fd-a90b-41cc-a88e-8788aa9c53a7.jpg)

zoom 3 OK
![_LNM_bug2](https://user-images.githubusercontent.com/46076619/140646992-657f7f6e-57b1-4677-a8ed-d5066174e2c7.jpg)

**Comment by albar965** [comment]
Sorry, this is a know issue with the hillshading data which I cannot fix since it's not mine.
It has more limitations as outlined in the appendix of the manual like missing coverage in New Zealand and far North and South.

For now there is only this black square in France known to me.
You can use another map like OpenTopoMap or StamenTerrain if you fly there often.
Alex
