### ISSUE TITLE
Random destination

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#88]
Add a function to propose a random destination based on the current distance search.

Could be extended to cover some functionality for the discontinued [SimFlightManager v1.4](https://www.reddit.com/r/flightsim/comments/5e5fi6/simflightmanager_v14/) or Destination Finder.

# Proposed solution

Put a context menu `Generate random flight plan from result` (or whatever makes sense) item into the airport search (probably other places too).

- Use the code here and generate and store a query string which returns airport id and coordinates for the current search result: https://github.com/albar965/littlenavmap/blob/e7e174d921375b1fe3a0a99ee89f0ecf39e00e98/src/search/sqlmodel.cpp#L455-L457
- Put a method into SqlModel and SqlQuery which executes above query string and returns a vector of structs containing airport id and lat/lon. May take a second or two.
- Once the user selects `Generate random flight plan from result`: Show a dialog which allows to define min and max distance for a flight.
- User presses `show flight` in above dialog:
  - Look at random pairs in id/lat/lon list until one within min/max distance found
  - Maybe remember id pairs in hash to avoid showing the same result
  - Keep in mind that not solution can be found (too small search result, etc.). Stop searching after five seconds (or whatever makes sense).
- Display departure and destination. On `Ok` fill flight plan (https://github.com/albar965/littlenavmap/blob/e7e174d921375b1fe3a0a99ee89f0ecf39e00e98/src/route/routecontroller.h#L151 and https://github.com/albar965/littlenavmap/blob/e7e174d921375b1fe3a0a99ee89f0ecf39e00e98/src/route/routecontroller.h#L154)

**Comment by u-an-i** [comment]
do you mean a right-click context menu? i think such would be too hidden.
I would put a row below the search result table containing the min, max fields and a button for "set random departure and destination from result".

![image](https://user-images.githubusercontent.com/84718885/131887321-3015a644-3f48-451e-b8bf-4b8ae8e5fdbd.png)

Perhaps I find a way to toggle the row, ie having a toggle "define random departure and destination from result" and then the min, max fields and a button "set to flight plan".

**Comment by albar965** [comment]
Agree. Quite hidden. Or an additional button on top. 
![grafik](https://user-images.githubusercontent.com/15254956/131899591-a1cc3a91-df60-4ce0-8b57-183e74b3fa3b.png)
I'd even put a menu item into the flight plan menu and/or the toolbar but I have no idea how to handle this.

**Comment by albar965** [comment]
Best solution IMO. Allows the user to hide the controls for this feature. We can change it to show up per default on a new or updated installation.
![grafik](https://user-images.githubusercontent.com/15254956/131917853-edb77f10-f7ae-4fe4-9ecc-5ec8af4ccc99.png)

**Comment by u-an-i** [comment]
i have troubles finding where the sql result is stored and thinking how it could be converted to a mapairport as you apparently do for display in the tableview because there every row has an airport context menu available.

i have followed `createAirportSearch` from `mainwindow.cpp` which in turn creates an `AirportSearch` and does `postCreateSearch`.
The `AirportSearch` constructor sets up some columns, one of them contains the ui `checkBoxAirportLightSearch` which is the only place in the whole project where I found this checkbox referenced (apart from its init) (and which is the first string I searched for when beginning this endeavour) so I wondered how a checkbox change triggers a search result update as it apparently does. Now `AirportSearch` continues setting some "variables" such as controller and model.
`postCreateSearch` lets connect some slots (but not the aforementioned checkbox), which is the main thing it does.

Inside `postCreateSearch` I found the Reset connection to `SearchBaseTable::resetSearch` which in turn lets call `SqlModel::buildQuery()`.
Now this finally lets call the `QSqlQueryModel::setQuery`, but which also "only" lets set values.

But nowhere did I find "go", "start", "operate on the set values".

I read the documentation on `QAbstractItemModel` and `QTableView` beacuse I guess such things are "intrinsicly" handled and I found the `data()` method which shall provide the data to the tableview and which you override in `SqlModel`. But that returns a `QVariant`, no `MapAirport`.

Now my questions are: how can I access the result list which I think "must" exist in some sort and is the basis for the table view result display and how would I transform those results into `MapAirport`? (Or does the table view only have the sqlquery and does internal caching of the result for display thus I would have to transform the query return values myself by execution of the query with a `QSqlQueryModel` programmatically?)

If you think helping me here is as quick as doing it yourself, i'm not unhappy if you implement it. I have the ui already setup according to your latest screenshot and can commit it to the PR.

Thank you (as always -- even if I did not mention it) for your great work!

**Comment by albar965** [comment]
The part of SqlModel I mentioned above is called for each change in the search. I'd generate the SQL string in this place and store it in a field. You can safely ignore all other methods you mentioned. No need to follow all the functionality and no need to look for a start. 
I can add the functionality which loads and returns the airport id/coordinate structs. No prob.

The search is one of the earliest implementations in this project and a bit overdone and over-complicated. The used Qt classes don't make it easier. QTableView, QItemModel and related are a mess IMO.

**Comment by albar965** [comment]
Committed changes in SqlModel and added all UI elements. The skeleton for implementation is https://github.com/albar965/littlenavmap/blob/00548892e7ce4d69f0535e322d69bff9888fd6fb/src/search/airportsearch.cpp#L743-L757

To load the plan fill a atools::fs::pln::Flightplan object use the following snippet to generate the route:
https://github.com/albar965/littlenavmap/blob/00548892e7ce4d69f0535e322d69bff9888fd6fb/src/gui/mainwindow.cpp#L2271-L2280

**Comment by u-an-i** [comment]
thank you very much! I think i can work with this.

**Comment by albar965** [comment]
This will make quite a few users happy. :smile:  I got this request several times but had no idea how to do it easily (until now).

**Comment by albar965** [comment]
Thanks for the help @u-an-i  :+1:
