### ISSUE TITLE
Flight Time

### ISSUE THREAD

**Issue by jwysong1** [albar965/littlenavmap#890]
Flight time is WAY off like x3 or x4 compared to the Garmin.  Used to be right on.

**Comment by albar965** [comment]
Sorry, but this issue is missing all kind of information:

1. LNM version.
2. Simulator
3. Flown aircraft
4. What Garmin, stock or add-on
5. Flight plan
6. Aircraft performance file

You can attach 5. and 6. if you add `.txt` to the files.

I rather suspect you're either using a broken or a wrong aircraft performance file. See here about [Aircraft Performance](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/AIRCRAFTPERF.html).

**Comment by jwysong1** [comment]
Also - LNM just updated... does it not keep the acft config file or does it go back to a generic one???
Thx - Joel
________________________________

**Comment by albar965** [comment]
> does it not keep the acft config file or does it go back to a generic one???

I keeps the last loaded but you can also find this out yourself by looking at the fuel report page.

What about my points above? Can I get the files?

**Comment by jwysong1** [comment]
Hi Alex -
The DC-6 performance file was not the current one.. Go figure.  I reinstalled it and all should be good.
All the best... more donations coming your way.......... GREAT software...   😉
Joel
________________________________

**Comment by albar965** [comment]
> The DC-6 performance file was not the current one.. Go figure. I reinstalled it and all should be good.

I see. 

I'd rather do a menu -> `Aircraft` -> `Merge collected performance` from time to time and check the actual values if they match the aircraft.

Alex
