### ISSUE TITLE
No more elevation profile prediction

### ISSUE THREAD

**Issue by stocky789** [albar965/littlenavmap#937]
Ever since the newest update released the elevation profile is no longer showing the little green line that predicts your elevation angle. Could this please be readded or fixed if it is bugged?

**Comment by albar965** [comment]
Did you check if it's enabled in the context menu of the elevation profile?

**Comment by stocky789** [comment]
> Did you check if it's enabled in the context menu of the elevation profile?

Sorry which context menu? It was always just on by default before

**Comment by albar965** [comment]
> Sorry which context menu? It was always just on by default before

The context menu of the elevation profile, of course. Right click on the profile and check if "Show vertical track" is selected.
I change or delete settings in some cases when starting an updated version the first time. This is needed since some settings are not compatible across different versions.
![image](https://user-images.githubusercontent.com/15254956/194033383-8707c5e6-76df-4bbb-b022-6694d7c32028.png)

**Comment by stocky789** [comment]
Well that makes sense. This new version doesn't have it 

When I right click that is literally the only option that does not show 

![image](https://user-images.githubusercontent.com/113968354/194046651-58782edb-8147-4412-9c18-a1e5cd5ee084.png)

**Comment by stocky789** [comment]
> Ok. I supposed you used LNM 2.8.0.beta since this feature is only present in this version. It's not in the stable 2.6.19. Now which version of LNM do you use?

Ahh okay that makes sense too. Sorry I'm new to LNM so haven't used any other version besides the one that had an elevation profile. Then I thought I upgraded it to a new version but it looked weird so i reverted back to stable 

But i must have had the 2.8.0 beta to begin with.

**Comment by albar965** [comment]
Settings can go lost or change if you switch between versions. That's why I recommend this to run them in parallel:
https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/INSTALLATION.html#multiple-installations

I think this is fixed. Closing. Feel free to reopen if something gets lost.

Alex
