### ISSUE TITLE
"Add-On Recognition settings" following symlinks while "Add-on Recognition does not on MAP"

### ISSUE THREAD

**Issue by cowreth** [albar965/littlenavmap#939]
LNM version : 2.8.0 beta
Simulator : MSFS

What happens : 
- when adding a path to exclude from Add-On Recognition, the tool follow simlinks
- hence, the airport is displayed as a Add-On on the map
- but when clicking on the airport, the "Data Source" is the link itself, not the destination of the link

Example : 
- it happens to me with GSX Pro
  - which install getways in the COMMUNITY Folder
  - but do so by linking to its internal directory
- when trying to add GSX link in the community folder for add-on exclusion, it resolves the link and add the "wrong" folder (or, actually, one that is not matched by add-on recognition

![image](https://user-images.githubusercontent.com/4106263/194759866-e33b5bf5-409b-4df7-b306-8cc9ede6728f.png)
Description : 
- on the left part, you can see Airport Overview (from this Information Docked Window), with Data Source not resolving the symlink
- in the middle, you can see CORK as being flagged as Add-on (yellow ring)
- on the right, the Add-On recognition path, being resolved

**Comment by albar965** [comment]
Fixed with albar965/atools@9fe655fb1c9213dbed3119a5b23ac59bbe668457 and more commits for the upcoming 2.8.1.beta.
Tested this with symbolic links on all OS, Windows shortcuts (lnk files) and Windows junctions with airport path display and exclude folders.

This should also fix the issues with GSX folders.

I'm closing the issue but reopen it in any case if you still see the issue after the 2.8.1.beta release.
