### ISSUE TITLE
Feature request: ATIS

### ISSUE THREAD

**Issue by anonymous555** [albar965/littlenavmap#998]
Show somewhere the digital ATIS

It's available here.

https://datis.clowd.io/

**Comment by albar965** [comment]
> **Delete this text after reading before posting the issue.**
I did. :slightly_smiling_face: 

ATIS information is already shown in raw form in LNM information window in tab `Airport` -> `Overview` and in tooltips.

[datis.clowd.io/](https://datis.clowd.io/) is not  suitable since it contains only North American airports.

More information like NOTAMs is planned for a far future version.
